/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отправка письма на почту об окончании кластеризации */
        "Robot_2.Methods.MailClaster.Add": {
            /** ID проекта */
            project_id: number;
            /** ID папки */
            folder_id: number;
            /** Название поисковика, по которому была запущена кластеризация */
            searcher: string;
            /** Ключ региона */
            region_key: string;
            /** Язык региона */
            region_lang: string;
            /** Количество ключевых слов */
            count_keywords: number;
            /** Степень кластеризации */
            counts: string;
            /** Тип кластеризации */
            type?: number;
            /** Base64-кодированное содержимое ZIP-файла, которое будет прикреплено к письму */
            zip_file_data: string;
        };
        "Robot_2.Methods.MailClaster.Add.Exec": boolean | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
