/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип массива: Date[]
         * @description @extends AbstractStringArray<Date>
         *     @method Date[] getValues()
         *     @method Date current()
         *     @see \TV\API\Types\Date
         */
        "TV.API.Types.DateArray": components["schemas"]["TV.API.Types.Date"][];
        /**
         * Дата
         * @example 2000-01-01
         */
        "TV.API.Types.Date": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
