/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение общей информации о проверках
         * @description - только для проверки, которая не завершена
         *     - в ответе будут заменены значения кодов ответа на текущие: count_000, count_1xx, count_2xx, count_3xx, count_4xx, count_5xx
         *     - в ответе будет заменено значение count_pages и count_all на текущие
         *     - в ответ будет добавлены значения robot_step и robot_count_tasks_allм
         */
        "Audit_2.Methods.Audit.Checks.Get": {
            /** Добавить в результат данные о незавершенной проверке */
            show_raw_data?: boolean;
            /**
             * Определяет формат результата: коллекция, объект, значение
             * @description Примеры:
             *     - fetchAll - получить коллекцию объектов
             *     - fetch - получить один объект
             *     - fetchColumn - получить свойсвто объекта
             */
            fetch_style?: import('../../../../Selector/Types/FetchStyle.ts').components['schemas']['Selector.Types.FetchStyle'] | null;
            /** ID проекта */
            project_id: number;
            /**
             * Список полей объекта, которые надо вернуть в результате
             * @description Если запрос поддерживает параметр `fetch_style`, формат ответа может быть разным, `fields` будет влиять на содержание данных в этом ответе
             *
             *     Использует поля модели
             */
            fields?: unknown[];
            /**
             * Список полей объекта, по которым необходимо выполнить сортировку
             * @description Поля могут быть строками или объектом: {name: string, direction: 'ASC' | 'DESC', orderValues: array, operator: string, values: array}
             *
             *     Использует поля модели
             */
            orders?: unknown[];
            /**
             * Список фильтров по полям объекта
             * @description {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             * @description Только для моделей с полем id
             */
            id?: number | null;
            /**
             * Количество объектов, которые необходимо получить в результате
             * @description Используется в паре с offset
             */
            limit?: number | null;
            /**
             * Число объектов, которое необходимо пропустить при получении результата
             * @description Используется в паре с limit
             */
            offset?: number;
        };
        /** Список выполненных (выполняемых) проверок аудита */
        "Audit_2.Methods.Audit.Checks.Get.Exec": unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
