/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип диаграммы
         * @enum {string}
         */
        "Snapshots_2.Types.History.Links.ChartType": Snapshots_2TypesHistoryLinksChartType;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Snapshots_2TypesHistoryLinksChartType {
    Tops = "tops",
    TopsCount = "tops_count",
    Avg = "avg",
    Visibility = "visibility",
    Median = "median"
}
export type operations = Record<string, never>;
