/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отправить тестовый отчет
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Reports_2\Methods\Positions\SendTest\Edit */
        "Reports_2.Methods.Positions.SendTest.Edit": {
            /** Id проекта, по которому необходимо отправить тестовый отчет */
            project_id: number;
        };
        "Reports_2.Methods.Positions.SendTest.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
