/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Tickets_2\Methods\Admin\Ticket\Edit */
        "Tickets_2.Methods.Admin.Ticket.Edit": {
            id: number;
            /** Флаг того, что тикет важный */
            is_important?: boolean | null;
            /** Номер задачи redmine, связанной с тикетом */
            task_id?: number | null;
            /** Доступные теги тикета */
            tags?: import('../../../../Tags_2/Types/TagsIds.ts').components['schemas']['Tags_2.Types.TagsIds'] | null;
            /** Статус тикета */
            status?: boolean | null;
        };
        "Tickets_2.Methods.Admin.Ticket.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
