/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование тикета (для админов) */
        "Tickets_2.Methods.Admin.Ticket.Edit": {
            id: number;
            /** Флаг того, что тикет важный */
            is_important?: boolean | null;
            /** Номер задачи redmine, связанной с тикетом */
            task_id?: number | null;
            /** Доступные теги тикета */
            tags?: components["schemas"]["Tags_2.Types.Tags"] | null;
            /** Статус тикета */
            status?: boolean | null;
        };
        /**
         * Доступные теги
         * @enum {string}
         */
        "Tags_2.Types.Tag": "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20";
        /**
         * Массив номеров тегов
         * @description Тип массива Tags[]
         *
         *     @see Tags_2\Types\Tag
         */
        "Tags_2.Types.Tags": components["schemas"]["Tags_2.Types.Tag"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
