/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Ai.Tracker.Prompts": {
            "COUNT(*)"?: unknown;
            "tagsNames()"?: unknown;
            id?: unknown;
            project_id?: unknown;
            group_id?: unknown;
            tags?: unknown;
            ord?: unknown;
            name?: unknown;
            group_name?: unknown;
            group_ord?: unknown;
            date?: unknown;
            model?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "date",
             *         "model",
             *         "project_id"
             *       ]
             *     } */
            response?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "date",
             *         "model",
             *         "project_id"
             *       ]
             *     } */
            mentioned?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
