/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение данных сводки для отображения графика */
        "Positions_2.Methods.Summary.Chart.Get": {
            /** Индекс региона */
            region_index: number;
            /** ID конкурентов */
            competitors_ids?: import('../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /** Даты для получения сводки */
            dates?: import('../../../../TV/API/Types/DateArray.ts').components['schemas']['TV.API.Types.DateArray'] | null;
            /** С какого числа получить данные
             *
             *     Необязательно, если указано dates */
            date1?: import('../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /** По какое число получить данные
             *
             *     Необязательно, если указано dates */
            date2?: import('../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Период дат
             *
             *     Не работает при указании dates
             * @default 2
             */
            type_range?: number;
            /**
             * Количество дат
             *
             *     Не работает при указании dates
             * @default 31
             */
            count_dates?: number;
            /** Отобразить данные по топам */
            show_tops?: boolean;
            /** Отобразить среднюю позицию */
            show_avg?: boolean;
            /** Отобразить медианную позицию */
            show_median?: boolean;
            /** Отобразить видимость */
            show_visibility?: boolean;
            only_exists_first_date?: import('../../../Types/OnlyExistsFirstDate.ts').components['schemas']['Positions_2.Types.OnlyExistsFirstDate'];
            /** При фильтрации по ID папок также искать в подпапках */
            group_folder_id_depth?: boolean;
            filters?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
            project_id: import('../../../../TV/API/Params/ProjectIdTrait.ts').components['schemas']['TV.API.Params.ProjectIdTrait']['project_id'];
        };
        "Positions_2.Methods.Summary.Chart.Get.Exec": unknown[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
