/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение региона */
        "Positions_2.Methods.Searchers.Regions.Edit": {
            /** Id проекта */
            project_id: number;
            /** Регион, который требуется изменить */
            region_index: number;
            /**
             * Язык региона
             *
             *     Для разных ПС список языков разный
             */
            region_lang?: string | null;
            /** Устройство региона */
            region_device?: import('../../../Types/RegionDevice.ts').components['schemas']['Positions_2.Types.RegionDevice'] | null;
            /**
             * Глубина региона
             *
             *     - 1-3 для Яндекса (ПК)
             *     - 1-10 для Google
             *     - 1-3 для GooglePlay
             */
            region_depth?: number | null;
            /** Включен */
            enabled?: boolean | null;
            filters?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
        };
        "Positions_2.Methods.Searchers.Regions.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
