/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавить регионы Google в сервис */
        "Admin_2.Methods.Actions.Regions.CommitGoogle.Edit": {
            /**
             * Список регионов в формате:
             *
             *     - Яндекс lr, укажите 0, если региона в Яндексе нет
             *     - Criteria ID: id региона в google
             *     - coords: координаты
             *     - name_ru: имя региона
             *     - areaName_ru: имя родительского региона, обычно это область
             * @description @type array<array{lr: int, criteriaId: int, coords: string, name_ru: string, areaName_ru: string}>
             */
            regions: (string | number)[];
            /** Являеется ли запуск - тестом */
            test: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
