/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение настроек бренда */
        "Projects_2.Methods.Competitors.Brand.Edit": {
            /** ID конкурента */
            id: number;
            /**
             * Имя бренда
             * @description Участвует в поиске в ответе ИИ
             */
            name?: string | null;
            /** Дополнительные имена бренда */
            aliases?: import('../../../../TV/API/Types/StringArray.ts').components['schemas']['TV.API.Types.StringArray'] | null;
            /** ID проекта */
            project_id: number;
        };
        /** Сохранить настройки бренда */
        "Projects_2.Methods.Competitors.Brand.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
