/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение даты проверок по заданному критерию (последние 12) */
        "Competitors_2.Methods.Dates.Get": {
            /** Индекс региона (не путать с ключом региона) */
            region_index: number;
            /** - ключевая фраза или ее часть (by_type = keyword)
             *     - url (by_type = url) */
            query: string;
            by_type: import('../../Types/ReportType.ts').components['schemas']['Competitors_2.Types.ReportType'];
            /** Дата проверки */
            date?: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
        };
        "Competitors_2.Methods.Dates.Get.Exec": unknown[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
