/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавление отпуска для сотрудника */
        "Admin_2.Methods.Staff.Vacation.Add": {
            /** ID юзера */
            user_id: number;
            /** Дата начала */
            date1: components["schemas"]["TV.API.Types.Date"];
            /** Дата окончания */
            date2: components["schemas"]["TV.API.Types.Date"];
            /** Тип
             *
             *     - vacation
             *     - day_off */
            type: (string | number)[];
        };
        /**
         * Дата
         * @example 2000-01-01
         */
        "TV.API.Types.Date": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
