/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Audit_2.Params.Wathcer.CheckIdTrait": {
            /** ID проверки радара */
            check_id: number;
        };
    };
    responses: never;
    parameters: {
        /** @description ID проверки радара */
        check_id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
