/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Users_2\Methods\Profile\Pass\Edit */
        "Users_2.Methods.Profile.Pass.Edit": {
            /** Текущий пароль */
            pass: string;
            /** Новый пароль */
            pass_new: string;
            /** Повтор нового пароля */
            pass_new_confirm: string;
        };
        "Users_2.Methods.Profile.Pass.Edit.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
