/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение темы сайта */
        "Users_2.Methods.Profile.Theme.Edit": {
            theme: import('../../../Types/Profile/Theme.ts').components['schemas']['Users_2.Types.Profile.Theme'];
        };
        "Users_2.Methods.Profile.Theme.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
