/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отправка правил на проверку
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Mentions_2\Methods\Checker\Go\Edit */
        "Mentions_2.Methods.Checker.Go.Edit": {
            /** Ключи источников (фильтр) */
            searchers_keys?: import('../../../Types/SearchersKeys.ts').components['schemas']['Mentions_2.Types.SearchersKeys'] | null;
        };
        "Mentions_2.Methods.Checker.Go.Edit.Exec": {
            rulesIds: unknown[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
