/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение статистики по работе распознавателей капч.
         *
         *     Статистика возвращается только для Google
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Robot_2\Methods\Admin\StatsRecognizers\Get */
        "Robot_2.Methods.Admin.StatsRecognizers.Get": {
            /** Дата отчета */
            date?: import('../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /** ID слоя */
            layer_id?: number | null;
            /** Имя разгадывателя */
            recognizer?: string | null;
            /** Включать в отчет только указанную ошибку */
            info?: string | null;
        };
        "Robot_2.Methods.Admin.StatsRecognizers.Get.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
