/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип: float[]
         * @deprecated
         * @description
         *     @extends AbstractTypedArray<float>
         *     @method float[] getValues()
         *     @method float current()
         */
        "TV.API.Types.FloatArray": number[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
