/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Номер метрики
         * @enum {integer}
         */
        "Projects_2.Types.Analytics.Axe": Projects_2TypesAnalyticsAxe;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Projects_2TypesAnalyticsAxe {
    // Видимость
    Visibility = 1,
    // Средняя позиция
    AveragePosition = 2,
    // Позиции
    Positions = 3,
    // Топ
    Top = 4,
    // Трафик
    Traffic = 11,
    // Ссылки
    Links = 12,
    // Индексация
    Indexing = 13
}
export type operations = Record<string, never>;
