/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Users.Ranks": {
            "IS_VISIBLE()"?: unknown;
            "IS_ACTIVE()"?: unknown;
            id?: unknown;
            category?: unknown;
            name?: unknown;
            descr?: unknown;
            descr_how_to_use?: unknown;
            bonus?: unknown;
            currency?: unknown;
            cashback_expenses?: unknown;
            cashback_first_payment?: unknown;
            discount?: unknown;
            color?: unknown;
            image_url?: unknown;
            always_visible?: unknown;
            code?: unknown;
            used?: unknown;
            date?: unknown;
            retention_week?: unknown;
            retention_month?: unknown;
            payment_week?: unknown;
            payment_month?: unknown;
            payment_month_6?: unknown;
            payment_year?: unknown;
            new_user?: unknown;
            returned_user?: unknown;
            quitted_user?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
