/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Keywords_2.Methods.Magnet.Import.Get": {
            provider: import('../../../Types/Magnet/Provider.ts').components['schemas']['Keywords_2.Types.Magnet.Provider'];
            /** Импортировать целевые ссылки */
            need_import_targets?: boolean;
            /** Id папки для импорта */
            folder_id?: number;
            /** Id группы для импорта */
            group_id?: number;
            /** Имя группы для импорта */
            group_name?: string;
            /** Теги по умолчанию */
            tags: import('../../../../Tags_2/Types/TagsIds.ts').components['schemas']['Tags_2.Types.TagsIds'];
            /** Период для импорта */
            period: import('../../../../TV/API/Types/DateArray.ts').components['schemas']['TV.API.Types.DateArray'];
            /** Метод источника данных */
            method?: string;
            project_id: import('../../../../TV/API/Params/ProjectIdTrait.ts').components['schemas']['TV.API.Params.ProjectIdTrait']['project_id'];
            fields?: import('../../../../TV/API/Params/FieldsTrait.ts').components['schemas']['TV.API.Params.FieldsTrait']['fields'];
            orders?: import('../../../../TV/API/Params/OrdersTrait.ts').components['schemas']['TV.API.Params.OrdersTrait']['orders'];
            filters?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
            limit?: import('../../../../TV/API/Params/LimitTrait.ts').components['schemas']['TV.API.Params.LimitTrait']['limit'];
            offset?: import('../../../../TV/API/Params/OffsetTrait.ts').components['schemas']['TV.API.Params.OffsetTrait']['offset'];
        };
        "Keywords_2.Methods.Magnet.Import.Get.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
