/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменения подписки на следующий расчетный период
         *
         *     Изменение доступно только в рамках одной платежной системы
         *
         *     Если требуется изменить другие параметры подписки, это можно сделать через создание новой подписки.
         *     При создании новой подписки текущая подписка будет досрочно завершена, с выдачей скидки в пользу новой подписки */
        "Payments_2.Methods.Subscriptions.Next.Edit": {
            /** Id следующего плана подписки */
            subscription_plan_id?: string | null;
            /** Значение следующего цикла подписки */
            subscription_cycle?: import('../../../../Bank_2/Types/Subscriptions/Cycle.ts').components['schemas']['Bank_2.Types.Subscriptions.Cycle'] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
