/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение хлебных крошек статьи справки
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Content_2\Methods\Support\Breadcrumbs\Get */
        "Content_2.Methods.Support.Breadcrumbs.Get": {
            /** Параметры страницы статьи */
            page_params?: string[];
        };
        "Content_2.Methods.Support.Breadcrumbs.Get.Exec": import('../../../../Models/Pages.ts').components['schemas']['Models.Pages'][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
