/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип объявления
         * @description @see https://yandex.ru/dev/direct/doc/ru/objects/ad#types
         * @enum {string}
         */
        "Broker_2.Types.Ads.Type": Broker_2TypesAdsType;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Broker_2TypesAdsType {
    // Текстово-графическое (обычное) объявление
    Text = "TEXT_AD",
    // Смарт-баннер
    Smart = "SMART_AD",
    // Объявление для рекламы мобильных приложений
    MobileApp = "MOBILE_APP_AD",
    // Динамическое объявление
    DynamicText = "DYNAMIC_TEXT_AD",
    // Графическое объявление.
    Image = "IMAGE_AD",
    // Видеообъявление в кампаниях с типом «Текстово-графические объявления» или «Реклама мобильных приложений».
    CpcVideo = "CPC_VIDEO_AD",
    // Медийный баннер
    CpmBanner = "CPM_BANNER_AD",
    // Медийное видеообъявление (в кампании с типом «Медийная кампания»).
    CpmVideo = "CPM_VIDEO_AD",
    // Товарное объявление (в кампании с типом «Единая перфоманс кампания»).
    Shopping = "SHOPPING_AD",
    // Текстово-графическое (обычное) объявление
    Listing = "LISTING_AD"
}
export type operations = Record<string, never>;
