/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип объявления
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Broker_2\Types\Ads\Type
         * @description @see https://yandex.ru/dev/direct/doc/ru/objects/ad#types
         * @enum {string}
         */
        "Broker_2.Types.Ads.Type": "TEXT_AD" | "SMART_AD" | "MOBILE_APP_AD" | "DYNAMIC_TEXT_AD" | "IMAGE_AD" | "CPC_VIDEO_AD" | "CPM_BANNER_AD" | "CPM_VIDEO_AD" | "SHOPPING_AD" | "LISTING_AD";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
