/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Schedule_2.Methods.Del": {
            /**
             * Тип расписания
             * @description @see Schedule_2\Mods\Schedule::$availableTypes
             */
            type: string;
            /** Id объекта, к которому будет привязано расписание */
            target_id: number;
            /** Id второго объекта, к которому будет привязано расписание (для mentions) */
            target_id_2?: number | null;
        };
        /** @throws Exception */
        "Schedule_2.Methods.Del.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
