/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Привязать расписание к объекту
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Schedule_2\Methods\Edit */
        "Schedule_2.Methods.Edit": {
            /**
             * Каждый элемент содержит:
             *     - times: Массив времени, где каждый элемент — ассоциативный массив с ключами:
             *     - - hour: Час из перечисления доступных часов (см. $availableHours)
             *     - - minute: Минута из перечисления доступных минут (см. $availableMinutes)
             *     - days: Массив дней из перечисления доступных дней (см. $availableDays)
             * @description Массив расписания, содержащий элементы с данными о времени и днях.
             *     @see Schedule_2\Mods\Schedule::$availableHours
             *     @see Schedule_2\Mods\Schedule::$availableMinutes
             *     @see Schedule_2\Mods\Schedule::$availableDays
             */
            schedule: {
                times: {
                    hour: string;
                    minute: string;
                }[];
                days: string[];
            }[];
            /**
             * Тип расписания
             * @description @see Schedule_2\Mods\Schedule::$availableTypes
             */
            type: string;
            /** Id объекта, к которому будет привязано расписание */
            target_id: number;
            /** Id второго объекта, к которому будет привязано расписание (для mentions) */
            target_id_2?: number | null;
        };
        "Schedule_2.Methods.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
