/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Модель нейросети для AI-трекера
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Ai_2\Types\Tracker\Models
         * @description @extends API\Types\AbstractTypedArray<Ai_2\Types\Tracker\Model>
         *     @method Ai_2\Types\Tracker\Model[] getValues()
         *     @method Ai_2\Types\Tracker\Model current()
         *     @see Ai_2\Types\Tracker\Model
         */
        "Ai_2.Types.Tracker.Models": import('./Model.ts').components['schemas']['Ai_2.Types.Tracker.Model'][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
