/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Bank.Subscription": {
            /** @constant */
            readonly Texts_by_limit_name: {
                positions_check: {
                    name: "Rank checks";
                    description: "Example description";
                };
                positions_check_manual: {
                    name: "Manual rechecks";
                    description: "";
                };
                keywords_volumes: {
                    name: "Search volume";
                    description: "";
                };
                keywords_collect: {
                    name: "Keyword research";
                    description: "";
                };
                keywords_collect_hint: {
                    name: "Search suggestions";
                    description: "";
                };
                projects: {
                    name: "Projects";
                    description: "";
                };
                projects_rights: {
                    name: "Guest Users";
                    description: "";
                };
                positions_tasks: {
                    name: "Rank total tasks";
                    description: "";
                };
                projects_competitors: {
                    name: "Competitors";
                    description: "";
                };
                projects_archive: {
                    name: "Archived projects";
                    description: "";
                };
                api: {
                    name: "API";
                    description: "";
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
