/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Bank.Subscription": {
            /** @constant */
            readonly Texts_by_limit_name: {
                positions_check: {
                    name: "Rank checks";
                    description: "Example description";
                };
                positions_check_manual: {
                    name: "Manual rechecks";
                    description: "";
                };
                keywords_volumes: {
                    name: "Search volume";
                    description: "";
                };
                keywords_collect: {
                    name: "Keyword research";
                    description: "";
                };
                keywords_collect_hint: {
                    name: "Search suggestions";
                    description: "";
                };
                projects: {
                    name: "Projects";
                    description: "";
                };
                projects_rights: {
                    name: "Guest Users";
                    description: "";
                };
                positions_tasks: {
                    name: "Rank total tasks";
                    description: "";
                };
                projects_competitors: {
                    name: "Competitors";
                    description: "";
                };
                projects_archive: {
                    name: "Archived projects";
                    description: "";
                };
                api: {
                    name: "API";
                    description: "";
                };
            };
            /** @constant */
            readonly Get_more: "Get more";
            /** @constant */
            readonly Unlock: "Unlock";
            /** @constant */
            readonly Current_plan: "Your current plan";
            /** @constant */
            readonly Payment_method: "Payment method";
            /** @constant */
            readonly Next_billing: "Next billing";
            /** @constant */
            readonly Next_plan: "Next plan";
            /** @constant */
            readonly Update_plan: "Update plan";
            /** @constant */
            readonly Cancel_subscription: "Cancel subscription";
            /** @constant */
            readonly View_invoice: "View invoice";
            /** @constant */
            readonly Billing_history: "Your billing history";
            /** @constant */
            readonly No_billing_history_data: "You do not have any billing history.";
            /** @constant */
            readonly View_all: "View all";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
