/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение сводки числа партнеров по числу рефералов
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Admin_2\Methods\Affiliate\ReferrersByReferrals\Get
         */
        "Admin_2.Methods.Affiliate.ReferrersByReferrals.Get": {
            /** Год для сводки */
            year: number;
            /** Валюта партнеров */
            currency: import('../../../../TV/API/Types/Currency.ts').components['schemas']['TV.API.Types.Currency'];
        };
        "Admin_2.Methods.Affiliate.ReferrersByReferrals.Get.Exec": {
            series: {
                data: {
                    name: string;
                    y: number;
                    range: number[];
                }[];
                name: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
