/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение приоритета задач */
        "Admin_2.Methods.Actions.Robot.Priority.Edit": {
            /** ID сайта или проекта */
            siteOrProjectId?: string | null;
            /** ID пользователя */
            userId?: number | null;
            /** Приоритет */
            priority: number;
            /**
             * Для чего изменяется приоритет
             * @default positions
             */
            for: string;
            /** Являеется ли запуск - тестом */
            test: boolean;
        };
        "Admin_2.Methods.Actions.Robot.Priority.Edit.Exec": import('../../../../Objects/Actions/Result.ts').components['schemas']['Admin_2.Objects.Actions.Result'];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
