/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование ссылки проекта */
        "Projects_2.Methods.Projects.Url.Edit": {
            /** ID проекта */
            id: number;
            /** Новая ссылка */
            url: import('../../../../TV/API/Types/Url.ts').components['schemas']['TV.API.Types.Url'];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
