/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип подписки
         *
         *     Определяет способ списания средств и порядок продления подписки
         * @enum {string}
         */
        "Bank_2.Types.Subscriptions.Type": Bank_2TypesSubscriptionsType;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Bank_2TypesSubscriptionsType {
    // Автоматическое продление с авто списанием; Например: рекуррентные платежи по карте
    Auto = "auto",
    // Ручное продление с участием покупателя; Например:; - платежи по карте без авто продления; - оплата по счету
    Manual = "manual"
}
export type operations = Record<string, never>;
