/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование текста ответа в тикете, только для админов */
        "Tickets_2.Methods.Admin.Message.Edit": {
            /** ID редактируемого сообщения тикета */
            id: number;
            /** Текст сообщения */
            text: string;
        };
        "Tickets_2.Methods.Admin.Message.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
