openapi: 3.0.3
info:
  title: Example
  version: 1.0.0
paths:
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      xml:
        name: category