openapi: 3.0.3
info:
  title: Example
  version: 1.0.0
paths:
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        username:
          type: string
          example: fehguy
        address:
          type: array
          xml:
            name: addresses
            wrapped: true
          items:
            $ref: 'Address.yaml#/components/schemas/Address'
      xml:
        name: customer