openapi: 3.0.3
info:
  title: Example
  version: 1.0.0
paths:
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag