/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Positions_2.Mods.Searchers.Interfaces.Searcher": {
            project_id?: number | null;
            id: number;
            searcher: number;
            key: number;
            name: string;
            regions: import('./Region.ts').components['schemas']['Positions_2.Mods.Searchers.Interfaces.Region'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
