/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип вопроса
         * @enum {string}
         */
        "Quiz_2.Types.Questions.Type": Quiz_2TypesQuestionsType;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Quiz_2TypesQuestionsType {
    // Можно выбрать только один ответ из представленных
    One = "ONE",
    // Можно выбрать несколько ответов из представленных
    Several = "SEVERAL",
    // Варианты ответа не представ алены, нужно написать ответ самостоятельно
    Text = "TEXT"
}
export type operations = Record<string, never>;
