/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Analytics.Ranks": {
            "ACTIVATIONS()"?: unknown;
            id?: unknown;
            name_ru?: unknown;
            name_en?: unknown;
            bonus_RUB?: unknown;
            bonus_USD?: unknown;
            to_date?: unknown;
            limit?: unknown;
            site?: unknown;
            code?: unknown;
            retention_week?: unknown;
            retention_month?: unknown;
            payment_week?: unknown;
            payment_month?: unknown;
            payment_month_6?: unknown;
            payment_year?: unknown;
            new_user?: unknown;
            returned_user?: unknown;
            quitted_user?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
