/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Sites.Thundo.Admin": {
            /** @constant */
            readonly Warning_message: "";
            /** @constant */
            readonly Warning_message_admin?: "Это пример растяжки с <span style=\"color: red;\">маркетинговыми новостями</span>. <a href=\"https://t.me/thundo_com\" target=\"_blank\">Это телеграм Thundo</a> (кстати, подписывайтесь). Щас будет перенос👇<br><br>Это <b>пример жирного текста</b> с эмодзи 😀🤗😜🫶🧡";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
