/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Audit_2\Methods\Indexing\Links\Get */
        "Audit_2.Methods.Indexing.Links.Get": {
            /** Диапазон значений шаблона */
            template_date_range: string;
            /** Произвольные даты без использования диапазона */
            dates?: unknown[] | null;
            /** Дата начала диапазона */
            date1?: string | null;
            /** Дата окончания диапазона */
            date2?: string | null;
            /**
             * Тип диапазона дат
             * @default 7
             */
            type_range?: import('../../../Types/Indexing/TypeRange.ts').components['schemas']['Audit_2.Types.Indexing.TypeRange'] | null;
            /** Количество дней в диапазоне */
            count_dates?: number | null;
            /** Ппоисковые ключи */
            searchers_keys?: unknown[] | null;
            /** Теги */
            tags?: unknown[] | null;
            /** Динамический */
            dynamic?: unknown[] | null;
            /** Динаамические данные */
            data_dynamic?: unknown[] | null;
            /** Сортировка данных */
            data_sort?: unknown[] | null;
            project_id: import('../../../../TV/API/Params/ProjectIdTrait.ts').components['schemas']['TV.API.Params.ProjectIdTrait']['project_id'];
        };
        /** Короткая гостевая ссылка на просмотр позиций */
        "Audit_2.Methods.Indexing.Links.Get.Exec": string | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
