/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение стоимости перекластеризации */
        "Keywords_2.Methods.Claster.Checker.Reclaster.Price.Get": {
            /** Отображать сумму с учетом скидки */
            apply_discount?: boolean;
            count: import('../../../../../Types/Claster/Degrees.ts').components['schemas']['Keywords_2.Types.Claster.Degrees'];
            /** ID проекта */
            project_id: number;
        };
        "Keywords_2.Methods.Claster.Checker.Reclaster.Price.Get.Exec": {
            pricesByUsers: {
                [key: string]: {
                    price: number;
                    priceOriginal: number;
                    limits: number;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
