/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение отчета платежей по сервисам */
        "Admin_2.Methods.Analytics.Get": {
            /** Дата */
            date: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'];
            period: import('../../Types/Analytics/Segment.ts').components['schemas']['Admin_2.Types.Analytics.Segment'];
            currency: import('../../../TV/API/Types/Currency.ts').components['schemas']['TV.API.Types.Currency'];
            /**
             * Имя метрики
             *
             *     - sum
             *     - discount
             *     - count_users
             *     - su
             *     - su_common: Без учета валюты
             */
            field_name: string;
            /** Длина периода */
            limit?: number | null;
        };
        "Admin_2.Methods.Analytics.Get.Exec": {
            categories: string[];
            series: {
                name: string;
                data: number[];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
