/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип выдачи
         * @enum {string}
         */
        "Content_2.Types.Apometr.Action": Content_2TypesApometrAction;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Content_2TypesApometrAction {
    // Обычная выдача
    Normal = "0",
    // XML выдача
    Xml = "xml"
}
export type operations = Record<string, never>;
