/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение информации об SSL сертификате
         *     Возваращает объект с параметрами:
         *     - expire
         */
        "Projects_2.Methods.Status.Ssl.Get": {
            /** Домен */
            domain: import('../../../../TV/API/Types/Url.ts').components['schemas']['TV.API.Types.Url'];
        };
        "Projects_2.Methods.Status.Ssl.Get.Exec": {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
