/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Предполагаемое число страниц на вашем сайте
         *
         *     Выбираейте приблизительное занчение, например 100, 1000 или 10000 в зависимсоти от размеров вашего сйта
         *
         *     Это значение влияет на стоимость генерации карты сайта
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Audit_2\Types\Sitemap\MaxPages
         * @enum {integer}
         */
        "Audit_2.Types.Sitemap.MaxPages": 100 | 1000 | 10000 | 100000 | 150000 | 300000;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
