/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=I18n\Api\En */
        "I18n.Api": {
            /** @constant */
            readonly View_in_API_explorer: "View in API explorer";
            /** @constant */
            readonly Add_parameter: "Add parameter";
            /** @constant */
            readonly Add_parameter_array: "Add parameter (array)";
            /** @constant */
            readonly Select_data_to_return: "Select data to return (fields)";
            /** @constant */
            readonly Add_filter: "Add a filter (filters item)";
            /** @constant */
            readonly Add_sorting: "Add sorting (orders item)";
            /** @constant */
            readonly Set_limit: "Set limit";
            /** @constant */
            readonly Set_offset: "Set offset";
            /** @constant */
            readonly Ask_questions_get_answers: "Search documentation";
            /** @constant */
            readonly PHP_SDK_example_githab: "PHP SDK example on GitHub";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
