/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Calendar": {
            /** @constant */
            readonly Dw_1: "Mo";
            /** @constant */
            readonly Dw_2: "Tu";
            /** @constant */
            readonly Dw_3: "We";
            /** @constant */
            readonly Dw_4: "Th";
            /** @constant */
            readonly Dw_5: "Fr";
            /** @constant */
            readonly Dw_6: "Sa";
            /** @constant */
            readonly Dw_7: "Su";
            /** @constant */
            readonly Day_of_week_1: "Monday";
            /** @constant */
            readonly Day_of_week_2: "Tuesday";
            /** @constant */
            readonly Day_of_week_3: "Wednesday";
            /** @constant */
            readonly Day_of_week_4: "Thursday";
            /** @constant */
            readonly Day_of_week_5: "Friday";
            /** @constant */
            readonly Day_of_week_6: "Saturday";
            /** @constant */
            readonly Day_of_week_7: "Sunday";
            /** @constant */
            readonly months: "|january|february|march|april|may|june|july|august|september|october|november|december";
            /** @constant */
            readonly of_months: "|january|february|march|april|may|june|july|august|september|october|november|december";
            /** @constant */
            readonly in_months: "|january|february|march|april|may|june|july|august|september|october|november|december";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
