/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Common": {
            url_lang_prefix: string;
            /** @default Page Not Found */
            Page_404_text: string;
            /** @default You will be redirected <br> in */
            Page_404_text2: string;
            /** @default seconds */
            Page_404_sec: string;
            /** @default Access denied */
            Page_403_text: string;
            /** @default Page loading */
            openApp_text: string;
            /** @default Open application */
            openApp_text2: string;
            /** @default en */
            lang: string;
            /** @default US */
            lang_country: string;
            lang_url: string;
            /** @default ru */
            alternate_lang: string;
            /** @default RU */
            alternate_lang_country: string;
            /** @default /ru */
            alternate_lang_url: string;
            /** @default English */
            Lang_full: string;
            /** @default language */
            language: string;
            /** @default Language */
            Language: string;
            /** @default en_US */
            locale: string;
            /** @default m/d/Y */
            date_format: string;
            /** @default Tools for tracking, analyzing and measuring SEO performance */
            Description: string;
            /** @default Try out SEO & PPC Tools for keyword research, clustering, rank tracking and on-page optimization. Get better results from paid search and organic rankings! */
            Og_description: string;
            /** @default SEO & PPC Tools for better marketing. Highly recommended! */
            Og_description_invite: string;
            /** @default Ascending */
            Ascending: string;
            /** @default Descending */
            Descending: string;
            /** @default Voronezhskaya ul. */
            TV_address_street: string;
            /** @default Session security error, please <a href="/">refresh page</a> and try again */
            Message_session_security_error: string;
            /** @default We're upgrading our servers. The service is temporarily unavailable. Please, try again later */
            Message_dbh_remote: string;
            /** @default We're upgrading our servers. Tasks creating is temporarily unavailable. Please, try again later */
            Message_dbh_remote_error: string;
            /** @default We're upgrading this module's server, please, try again later */
            Message_ch_error: string;
            /** @default We're upgrading this module's server, please, try again later */
            Message_sp_error: string;
            /** @default Every day */
            Every_day: string;
            /** @default times */
            time_a_0: string;
            /** @default time */
            time_a_1: string;
            /** @default times */
            time_a_2: string;
            /** @default a week */
            a_week: string;
            /** @default a month */
            a_month: string;
            /** @default discount */
            discount: string;
            /** @default mo */
            month_short: string;
            /** @default Balance */
            Balance: string;
            /** @default Affiliate program */
            Referrals: string;
            /** @default Organization */
            Organization: string;
            /** @default Yes */
            Yes: string;
            /** @default Exists */
            Exists: string;
            /** @default No */
            No: string;
            /** @default not */
            not: string;
            /** @default and */
            and: string;
            /** @default rub. */
            ruble: string;
            /** @default for */
            for: string;
            /** @default For */
            For: string;
            /** @default Close */
            Close: string;
            /** @default OK */
            OK: string;
            /** @default OK */
            Apply: string;
            /** @default Apply */
            Choose: string;
            /** @default Download */
            Download: string;
            /** @default download */
            download: string;
            /** @default Step */
            Step: string;
            /** @default Continue */
            Continue: string;
            /** @default Back */
            Back: string;
            /** @default Next */
            Next: string;
            /** @default Prev */
            Prev_page_short: string;
            /** @default Next */
            Next_page_short: string;
            /** @default project */
            project: string;
            /** @default Project */
            Project: string;
            /** @default of project */
            of_project: string;
            /** @default Tool digest (2024) */
            Tool_digest: string;
            /** @default Ticket */
            Ticket: string;
            /** @default Tickets */
            Tickets: string;
            /** @default All tickets */
            All_tickets: string;
            /** @default All articles */
            All_pages: string;
            /** @default Submit */
            Submit: string;
            /** @default "Tickets" page */
            Tickets_page: string;
            /** @default Submitted */
            Submitted: string;
            /** @default Created */
            Created_at: string;
            /** @default No. */
            Schet_number: string;
            /** @default Cancel */
            Cancel: string;
            /** @default Send */
            Send: string;
            /** @default More */
            More: string;
            /** @default Read more */
            Read_more: string;
            /** @default User */
            User: string;
            /** @default Message */
            Message: string;
            /** @default Message hasn't been sent */
            Message_not_sended: string;
            /** @default Comment not removed */
            Comment_not_deleted: string;
            /** @default Link */
            Link: string;
            /** @default Name */
            Name: string;
            /** @default First and last name */
            First_and_last_name: string;
            /** @default Access denied */
            Access_denied: string;
            /** @default Access error */
            Access_error: string;
            /** @default No data found */
            No_data: string;
            /** @default No results */
            No_results: string;
            /** @default Dynamics */
            Dynamics: string;
            /** @default Country */
            Country: string;
            /** @default No. */
            Number: string;
            /** @default Number */
            Number_word: string;
            /** @default CPC */
            CPC: string;
            /** @default Clear */
            Clear: string;
            /** @default Phone number */
            Phone: string;
            /** @default Email */
            Email: string;
            /** @default The Email you entered doesn't exist */
            Email_not_exist: string;
            /** @default The password you entered is incorrect! */
            Password_incorrect: string;
            /** @default Enter email */
            Enter_email: string;
            /** @default Enter password */
            Enter_password: string;
            /** @default Remember me */
            Remember_me: string;
            /** @default Forgot your password? */
            Forgot_password: string;
            /** @default Sign up now */
            Signup_now: string;
            /** @default Sign in with */
            Sign_in_with: string;
            /** @default Recover password */
            Password_recovering: string;
            /** @default Recover password */
            Recover_password: string;
            /** @default Keywords (each keyword on a new line) */
            Keywords_one_per_line: string;
            /** @default Add a Search engine */
            Add_se: string;
            /** @default Create a project */
            Create_project: string;
            /** @default Creating... */
            Creating: string;
            /** @default Enter a valid E-mail address */
            Enter_valid_email_notice: string;
            /** @default No account? <a href="." data-to-view="%toViewReg%">Sign up</a> */
            No_account_sign_up: string;
            /** @default No account? */
            No_account: string;
            /** @default By pressing Sign up you accept <a href="%hrefConfirm%" target="_blank">Terms and Conditions</a> and <a href="%hrefPrivacy%" target="_blank">Privacy Policy</a> */
            Through_registration_you_confirm_agreement_policy: string;
            /** @default Already have an account */
            Already_have_account: string;
            /** @default <a href="." data-to-view="%toViewAuth%">Log in</a> or <a href="." data-to-view="%toViewReg%">sign up</a> */
            Try_again_or_sign_up: string;
            /** @default If you didn't receive a message, check a <b>Spam</b> folder or submit a ticket to <a href="%hrefCreateTicket%">Customer support</a> */
            If_no_msg_check_spam_ask_support_notice: string;
            /** @default If you didn't receive a message, check a <b>Spam</b> folder or submit a ticket to  */
            If_no_msg: string;
            /** @default Customer support */
            support_notice: string;
            /** @default A confirmation link has been sent to  */
            Confirmation_link_sent_to_email: string;
            /** @default Internal error occurred, please submit a report to the developers */
            Internal_error: string;
            /** @default Unknown error occurred, please try again later */
            Unknown_error: string;
            /** @default Google server error */
            Google_server_error: string;
            /** @default Yandex.API server error */
            Yandex_API_server_error: string;
            /** @default Error occurred! Please, contact the project owner to resolve the issue! */
            Yandex_auth_error: string;
            /** @default Required parameter missing in the request */
            Request_error_required: string;
            /** @default Passed parameter type mismatch */
            Request_error_type: string;
            /** @default Passed parameter value mismatch */
            Request_error_value: string;
            /** @default Passed qualifiers mismatch */
            Request_error_qualifiers: string;
            /** @default Regular expression error */
            Error_regexp: string;
            /** @default Valid characters */
            Valid_characters: string;
            /** @default Bonus */
            Bonus: string;
            /** @default or */
            or: string;
            /** @default until */
            to: string;
            /** @default to */
            to_1: string;
            /** @default at */
            at: string;
            /** @default Until */
            To: string;
            /** @default Up to  */
            Until: string;
            /** @default next */
            next_count: string;
            /** @default pages */
            pages: string;
            /** @default pages */
            pages_full: string;
            /** @default display */
            limit: string;
            /** @default by */
            by: string;
            /** @default Path */
            Path: string;
            /** @default Rule */
            Rule: string;
            /** @default Allow */
            Allow: string;
            /** @default Forbid */
            Disallow: string;
            /** @default Add mask matches from sitemap */
            Allow_of_mask: string;
            /** @default Forbid the mask */
            Disallow_of_mask: string;
            /** @default Search */
            Search: string;
            /** @default Examples */
            Examples: string;
            /** @default Start */
            Begin: string;
            /** @default Start over */
            Start_over: string;
            /** @default Export */
            Export: string;
            /** @default Import */
            Import: string;
            /** @default Off */
            Off: string;
            /** @default Changes */
            Changes: string;
            /** @default Change */
            Change: string;
            /** @default Value */
            Value: string;
            /** @default Hide */
            Hide: string;
            /** @default Display */
            Display: string;
            /** @default Save */
            Save: string;
            /** @default Time */
            Time: string;
            /** @default Loading */
            Loading: string;
            /** @default CY */
            CY: string;
            /** @default Bid manager */
            Broker: string;
            /** @default Page is under maintenance */
            Maintenance: string;
            /** @default to account */
            on_account: string;
            /** @default to */
            on: string;
            /** @default SEO Tools */
            Tools: string;
            /** @default Keyword research tool */
            Keyword_researcher: string;
            /** @default Rank tracker tool */
            Rank_tracker: string;
            /** @default Upload */
            Upload: string;
            /** @default Hide all */
            Hide_all: string;
            /** @default Expand all */
            Expand_all: string;
            /** @default Expand */
            Expand: string;
            /** @default Attention */
            Attention: string;
            /** @default from */
            from: string;
            /** @default from */
            from_1: string;
            /** @default dated */
            dated: string;
            /** @default from */
            fromDate: string;
            /** @default to */
            toDate: string;
            /** @default SE */
            SE: string;
            /** @default Guest link */
            Guest_link: string;
            /** @default Guest link copied to clipboard */
            Guest_link_copied_to_clipboard: string;
            /** @default PC */
            Device_0: string;
            /** @default Tablet */
            Device_1: string;
            /** @default Phone */
            Device_2: string;
            /** @default YandexBot/3.0 */
            Device_100: string;
            /** @default YandexBot/3.0 (mobile) */
            Device_102: string;
            /** @default Googlebot/2.1 */
            Device_110: string;
            /** @default Googlebot/2.1 (mobile) */
            Device_112: string;
            /** @default AdsBot-Google */
            Device_120: string;
            /** @default AdsBot-Google-Mobile */
            Device_122: string;
            /** @default Tag */
            Tag: string;
            /** @default Tags */
            Tags: string;
            /** @default All tags */
            All_tags: string;
            /** @default Charts */
            Charts: string;
            /** @default All */
            All: string;
            /** @default Selected */
            Selected: string;
            /** @default Select */
            Select: string;
            /** @default Select all */
            Select_all: string;
            /** @default Added */
            Added: string;
            /** @default Deleted */
            Deleted: string;
            /** @default Rename */
            Rename: string;
            /** @default On / Off */
            On_or_off: string;
            /** @default Autoselect */
            Autoselect: string;
            /** @default Open project */
            Open_project: string;
            /** @default Domain */
            Domain: string;
            /** @default Domains */
            Domains: string;
            /** @default Track */
            Track: string;
            /** @default Check */
            Check: string;
            /** @default Track */
            Track_continued: string;
            /** @default Telegram */
            Telegram: string;
            /** @default Link to Telegram */
            Link_to_telegram: string;
            /** @default Other */
            Other: string;
            /** @default Other */
            Other_f: string;
            /** @default Proceed */
            Proceed: string;
            /** @default Projects */
            Projects: string;
            /** @default Yandex.Metrica */
            Metrika: string;
            /** @default Yandex.Webmaster */
            Webmaster: string;
            /** @default Yandex Direct */
            Yandex_Direct: string;
            /** @default Yandex.Direct */
            YandexDirect: string;
            /** @default Yandex Wordstat */
            Yandex_Wordstat: string;
            /** @default Volume */
            Y_freq: string;
            /** @default "Volume" */
            Y_freq2: string;
            /** @default "!Volume" */
            Y_freq3: string;
            /** @default "[Volume]" */
            Y_freq5: string;
            /** @default "[!Volume]" */
            Y_freq6: string;
            /** @default "[Volume]" */
            G_freq2: string;
            /** @default "Volume" */
            M_freq2: string;
            /** @default 1st Premium */
            Y_price1: string;
            /** @default 2st Premium */
            Y_price2: string;
            /** @default Premium */
            Y_price3: string;
            /** @default 1st place */
            Y_price4: string;
            /** @default Guaranteed */
            Y_price5: string;
            /** @default Bid */
            G_price: string;
            /** @default Search engine */
            Search_engine: string;
            /** @default Search engines */
            Search_engines: string;
            /** @default Location */
            Region: string;
            /** @default location */
            region: string;
            /** @default Selected locations */
            Selected_regions: string;
            /** @default Compare */
            Compare: string;
            /** @default Folder */
            Folder: string;
            /** @default Group */
            Group: string;
            /** @default Visibility */
            Visibility: string;
            /** @default Avg.pos. */
            Average: string;
            /** @default Average position */
            Average_position: string;
            /** @default Add */
            Add: string;
            /** @default Create */
            Create: string;
            /** @default Move */
            Move: string;
            /** @default Delete */
            Delete: string;
            /** @default Repalce */
            Replace: string;
            /** @default Restore */
            Restore: string;
            /** @default Copy */
            Copy: string;
            /** @default Copy */
            Copy2: string;
            /** @default Delete */
            Remove: string;
            /** @default You will be charged */
            Charge: string;
            /** @default confirm */
            confirm: string;
            /** @default Confirm */
            Confirm: string;
            /** @default Delete selected */
            Delete_selected: string;
            /** @default Delete all */
            Delete_all: string;
            /** @default Traffic */
            Traffic: string;
            /** @default Rankings */
            Positions: string;
            /** @default Keyword */
            Keyword: string;
            /** @default Keyword */
            Key_word: string;
            /** @default Settings */
            Settings: string;
            /** @default URL Settings */
            Settings_URL: string;
            /** @default Important! This operation cannot be undone. */
            Irreversible: string;
            /** @default Missing */
            Empty_field: string;
            /** @default Notifications */
            Notification: string;
            /** @default My project */
            Personal_project: string;
            /** @default Terms of Service */
            Agreement: string;
            /** @default Period */
            Period: string;
            /** @default You cannot change project settings until tracking is completed */
            Config_is_readonly: string;
            /** @default locations */
            regions: string;
            /** @default types */
            types: string;
            /** @default Select date */
            Select_date: string;
            /** @default Not date */
            Not_date: string;
            /** @default Close window */
            Close_window: string;
            /** @default Dashboard */
            Dashboard: string;
            /** @default Help center */
            Support: string;
            /** @default URL shortener */
            Shortener: string;
            /** @default Journal */
            Journal: string;
            /** @default Academy */
            Academy: string;
            /** @default Pricing */
            Pricing: string;
            /** @default Sign up */
            Signup: string;
            /** @default Sign up */
            Sign_up: string;
            /** @default Sign up */
            Sign_up_2: string;
            /** @default Sign in */
            Sign_in: string;
            /** @default Sign in */
            Sign_in_account: string;
            /** @default Sign out */
            Sign_out: string;
            /** @default Server response */
            Server_response: string;
            /** @default Red */
            Red: string;
            /** @default Orange */
            Orange: string;
            /** @default Yellow */
            Yellow: string;
            /** @default Blue */
            Blue: string;
            /** @default Purple */
            Purple: string;
            /** @default Green */
            Green: string;
            /** @default Magenta */
            Magenta: string;
            /** @default Dark blue */
            Dark_blue: string;
            /** @default Turquoise */
            Turquoise: string;
            /** @default Volume */
            Frequency: string;
            /** @default Moscow */
            Moscow: string;
            /** @default Minsk */
            Minsk: string;
            /** @default Kyiv */
            Kyiv: string;
            /** @default London */
            London: string;
            /** @default New York */
            NewYork: string;
            /** @default St. Petersburg */
            StPetersburg: string;
            /** @default Almaty */
            Almaty: string;
            /** @default Russia */
            Russia: string;
            /** @default Ukraine */
            Ukraine: string;
            /** @default Kazakhstan */
            Kazakhstan: string;
            /** @default Belarus */
            Belarus: string;
            /** @default Amount */
            Sum: string;
            /** @default Date */
            Date: string;
            /** @default Week */
            Week: string;
            /** @default Month */
            Month: string;
            /** @default month */
            month: string;
            /** @default months */
            months: string;
            /** @default months */
            months_mult: string;
            /** @default 6 months */
            months_6: string;
            /** @default Quarter */
            Quarter: string;
            /** @default Year */
            Year: string;
            /** @default Total */
            Total: string;
            /** @default TOTAL */
            TOTAL: string;
            /** @default Yandex update */
            Yandex_update: string;
            /** @default code */
            "\u0441ode": string;
            /** @default Thank you! */
            Thank_you: string;
            /** @default Thank you for using our tools */
            Thank_you_for_using_our_tools: string;
            /** @default Since */
            Since: string;
            /** @default Till */
            Till: string;
            /** @default up to */
            till: string;
            /** @default Yandex */
            Yandex: string;
            /** @default Rank */
            Position: string;
            /** @default Impressions */
            Impressions: string;
            /** @default Demand */
            Demand: string;
            /** @default FAQ */
            FAQ: string;
            /** @default Frequently asked questions */
            Frequently_asked_questions: string;
            /** @default Owner */
            Owner: string;
            /** @default level */
            level: string;
            /** @default No payments yet */
            No_payments: string;
            /** @default Show legend */
            Show_legend: string;
            /** @default Hide legend */
            Hide_legend: string;
            /** @default Expand menu */
            Menu_expand: string;
            /** @default Minimize menu */
            Menu_unexpand: string;
            /** @default Search */
            Menu_dynamics_search: string;
            /** @default Rank Tracker */
            Menu_dynamics: string;
            /** @default SERP Snapshots */
            Menu_snapshots: string;
            /** @default My competitors */
            Menu_competitors: string;
            /** @default Keywords */
            Menu_phrases: string;
            /** @default Audit */
            Menu_audit: string;
            /** @default Overview */
            Menu_analytics: string;
            /** @default PPC */
            Menu_PPC: string;
            /** @default Yandex.Direct */
            Menu_broker: string;
            /** @default Settings */
            Menu_settings: string;
            /** @default More */
            Menu_more: string;
            /** @default Folders */
            Folders: string;
            /** @default Groups */
            Groups: string;
            /** @default Keywords */
            Keywords: string;
            /** @default keywords */
            of_keywords: string;
            /** @default folders */
            of_folders: string;
            /** @default projects */
            of_projects: string;
            /** @default for project */
            of_project1: string;
            /** @default for project */
            for_project: string;
            /** @default competitor */
            competitor: string;
            /** @default All groups */
            All_groups: string;
            /** @default All folders */
            All_folders: string;
            /** @default All locations */
            All_regions: string;
            /** @default All search engines */
            All_searchers: string;
            /** @default All projects */
            All_projects: string;
            /** @default Integration */
            Integration: string;
            /** @default update days */
            updates_days: string;
            /** @default the entire period */
            whole_period: string;
            /** @default two dates */
            two_dates: string;
            /** @default Project report for */
            Report_for_project: string;
            /** @default Time range */
            Interval: string;
            /** @default compare with competitors */
            competitors_comparison: string;
            /** @default Compare by search engine */
            Searchers_comparison: string;
            /** @default Compare by location */
            Regions_comparison: string;
            /** @default Your browser is not supported! */
            Browser_not_supported: string;
            /** @default Browser settings */
            Browser_settings: string;
            /** @default Service might be unstable */
            Service_may_go_unstable: string;
            /** @default Compatible browser is */
            Preferred_browser: string;
            /** @default Compare by */
            Comparison_by: string;
            /** @default Keywords */
            Phrases: string;
            /** @default TOP */
            TOP: string;
            /** @default Top */
            Top: string;
            /** @default Keyword dynamics */
            Phrases_dynamics: string;
            /** @default Project settings */
            Project_settings: string;
            /** @default Keywords in TOP */
            Phrases_in_TOP: string;
            /** @default Keywords in Top */
            Phrases_in_Top: string;
            /** @default Page */
            Page: string;
            /** @default page */
            page: string;
            /** @default last 10 days */
            last_10_days: string;
            /** @default last month */
            last_month: string;
            /** @default last update */
            last_check: string;
            /** @default last 2 updates */
            last_two_dates: string;
            /** @default last month (week's average) */
            last_month_week_average: string;
            /** @default similar keywords */
            also_searched: string;
            /** @default Sources */
            Sources: string;
            /** @default Clicks */
            Clicks: string;
            /** @default Other dates */
            Other_dates: string;
            /** @default Help */
            Help_center: string;
            /** @default Support Center */
            Help_center_welcome: string;
            /** @default Got any questions? */
            Help_center_question: string;
            /** @default Run */
            Run: string;
            /** @default Manage */
            Manage: string;
            /** @default Project id is missing */
            Missed_project_id: string;
            /** @default `Project_id` is missing */
            Missed_project_id2: string;
            /** @default Project analytics */
            Project_analytics: string;
            /** @default Keyword dynamics */
            Project_dynamics: string;
            /** @default Updates */
            Apometr: string;
            /** @default Google and Yandex SERP tracking tool */
            Apometr_title: string;
            /** @default Google and Yandex updates calendar (SERP updates and changes). Get SERP updates alerts. SERP updates score for different locations and content types. */
            Apometr_description: string;
            /** @default Google and Yandex SERP updates */
            Apometr_og_title: string;
            /** @default SERP updates score for different locations and content types. */
            Apometr_og_description: string;
            /** @default Get update alerts */
            Apometr_notice: string;
            /** @default Pricing */
            Pricing_title: string;
            /** @default Account */
            Profile_title: string;
            /** @default Bank */
            Bank_title: string;
            /** @default Your projects */
            Your_projects: string;
            /** @default Invalid file format (expected: %availableExtensionsNames%) */
            Incorrect_file_format: string;
            /** @default Maximum upload size exceeded (%maxSize%) */
            Max_size: string;
            /** @default Website SEO Audit tool */
            Audit: string;
            /** @default Tutorials */
            Tutorial: string;
            /** @default User ID */
            User_id: string;
            /** @default Managing executive */
            Managing_executive: string;
            /** @default Pustovoit */
            Pustovoit: string;
            /** @default Denis */
            Denis: string;
            /** @default Anatolyevich */
            Anatolyevich: string;
            /** @default Chief Executive Officer */
            CEO: string;
            /** @default office */
            office: string;
            /** @default Dot */
            Dot: string;
            /** @default Comma */
            Comma: string;
            /** @default Add manually */
            Enter_manually: string;
            /** @default max 10 Mb */
            max_10_mb: string;
            /** @default Checks schedule */
            Schedule_settings_checks: string;
            /** @default Reports schedule */
            Schedule_settings_reports: string;
            /** @default Basic */
            Basic: string;
            /** @default IP address */
            Address_IP: string;
            /** @default Phone number */
            Phone_number: string;
            /** @default Recipient */
            Recipient: string;
            /** @default  Federal act */
            Federal_act: string;
            /** @default optional */
            optional: string;
            /** @default Full name */
            Full_name_abbr: string;
            /** @default Mobile phone */
            Mobile_phone: string;
            /** @default not found */
            not_found: string;
            /** @default Try to <i class="a" data-action="reset_filters">reset</i> all filters<br><i class="archive_search">
             *     	or search <a href="/support/projects/archive" target="_blank" class="a">Archived</a> projects</i> */
            Try_to_reset_filters_or_search_archive_html: string;
            /** @default Print */
            Print: string;
            /** @default Contact us */
            Contact_us: string;
            /** @default Competitor research */
            Competitor_analysis: string;
            /** @default Top up your balance */
            Refill_balance: string;
            /** @default Median */
            Median: string;
            /** @default Reset */
            Reset: string;
            /** @default View */
            View: string;
            /** @default Pin bar */
            Bar_pin: string;
            /** @default Number */
            Count: string;
            /** @default Invalid URL format */
            Invalid_url: string;
            /** @default Access settings */
            Access_settings: string;
            /** @default Hide access settings */
            Hide_access_settings: string;
            /** @default Sort */
            Sort: string;
            /** @default No snippet */
            No_snippet: string;
            /** @default Copied to clipboard */
            Copied_to_clipboard: string;
            /** @default Cannot copied to clipboard */
            Cannot_copied_to_clipboard: string;
            /** @default Copy the guest link manually */
            Copy_guest_link_manually: string;
            /** @default Press */
            Press_to_copy_1: string;
            /** @default +C to copy a link */
            Press_to_copy_2: string;
            /** @default Guest link created */
            Guest_link_created: string;
            /** @default Please fill in all required fields */
            Need_fill_required_fields: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
