/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Cron": {
            /** @default Сommand */
            readonly Field_command: string;
            /** @default Description */
            readonly Field_description: string;
            /** @default Days of the week */
            readonly Field_days: string;
            /** @default Hours */
            readonly Field_hh: string;
            /** @default Minutes */
            readonly Field_i: string;
            /** @default On/Off */
            readonly Field_on: string;
            /** @default Task created */
            readonly Field_task_create_time: string;
            /** @default Task runned */
            readonly Field_task_start_time: string;
            /** @default Execution status */
            readonly Field_task_status: string;
            /** @default Disabled */
            readonly Disabled: string;
            /** @default Enabled */
            readonly Enabled: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
