/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Cron": {
            /** @constant */
            Field_command: "Сommand";
            /** @constant */
            Field_description: "Description";
            /** @constant */
            Field_days: "Days of the week";
            /** @constant */
            Field_hh: "Hours";
            /** @constant */
            Field_i: "Minutes";
            /** @constant */
            Field_on: "On/Off";
            /** @constant */
            Field_task_create_time: "Task created";
            /** @constant */
            Field_task_start_time: "Task runned";
            /** @constant */
            Field_task_status: "Execution status";
            /** @constant */
            Disabled: "Disabled";
            /** @constant */
            Enabled: "Enabled";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
