/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Fieldtemplates": {
            /** @default Manage columns */
            Title: string;
            /** @default Column */
            Column: string;
            /** @default List of recent columns */
            Last_columns_list: string;
            /** @default Save as new template */
            Save_as_new_template: string;
            /** @default save changes */
            save_changes: string;
            /** @default Added columns */
            Added_columns: string;
            /** @default Column settings */
            Columns_settings: string;
            /** @default Delete columns */
            Delete_columns: string;
            /** @default No columns added */
            No_columns_added: string;
            /** @default Advanced options */
            Advanced_options: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
