/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Pages": {
            /** @constant */
            readonly Checking_positions: "Rank Checking and Rank Tracking";
            /** @constant */
            readonly Collecting_top_sites: "SERP Top Checker";
            /** @constant */
            readonly Technical_analysis: "SEO Website Audit";
            /** @constant */
            readonly Tracking_changes: "Changer Tracker and Meta Tag Exractor";
            /** @constant */
            readonly Semantic_core_research: "Semantic Core Research";
            /** @constant */
            readonly Volume_checker: "Volume Checker";
            /** @constant */
            readonly Index_checker: "Index Checker";
            /** @constant */
            readonly Sitemap_generator: "Sitemap generator";
            /** @constant */
            readonly Bid_manager: "Bid Manager";
            /** @constant */
            readonly Updates_scanner: "Updates Scanner";
            /** @constant */
            readonly Shortener_url: "URL Shortener";
            /** @constant */
            readonly Clustering_top: "Clustering by SERP Top";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
