/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=I18n\Sitemap\En */
        "I18n.Sitemap": {
            /** @constant */
            readonly Settings: "Tool settings";
            /** @constant */
            readonly Popup_go_text_before_select_1: "Sitemap for";
            /** @constant */
            readonly Popup_go_text_before_select_2: "will contain up to";
            /** @constant */
            readonly Popup_go_text_before_price: "Project owner will be charged:";
            /** @constant */
            readonly Max_pages: "MAX number of pages";
            /** @constant */
            readonly Info_cost: "You will be charged";
            /** @constant */
            readonly Hint_not_checks_text: "Sitemap hasn't  been generated yet.<br>🗺️ <a href=\"/support/sitemap/\" target=\"_blank\">Why you need to generate sitemap →</a>";
            /** @constant */
            readonly Hint_not_checks_btn: "Generate sitemap";
            /** @constant */
            readonly You_will_be_charged: "You will be charged";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
