/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=I18n\Snapshots\En */
        "I18n.Snapshots": {
            /** @constant */
            readonly Snippets_in_snapshots: "Snippets in snapshots";
            /** @constant */
            readonly No_snapshots_these_dates_note: "No Snapshots saved for the applied filters and dates";
            /** @constant */
            readonly Snapshots_for_keyword: "Snapshots of";
            /** @constant */
            readonly Add_keyword_to_see_snapshot: "Add keyword to display search results Snapshot";
            /** @constant */
            readonly Add_keyword_to_compare: "Add keyword to compare Snapshots";
            /** @constant */
            readonly not_in_competitor_list: "not on the competitor list";
            /** @constant */
            readonly in_competitor_list: "on the competitor list";
            /** @constant */
            readonly To_manage_competitors_move: "To manage competitor websites, move to the";
            /** @constant */
            readonly move_to_settings: "Rank Tracker page and press a gear icon on the toolbar";
            /** @constant */
            readonly Read_competitor_help_article: "For more details read the Help center article <a href=\"/support/dynamics/competitors/\" target=\"_blank\">How to manage competitor websites?</a>";
            /** @constant */
            readonly Competitor_website: "Competitor website";
            /** @constant */
            readonly Save_snapshot_top_N: "Save a snapshot of TOP";
            /** @constant */
            readonly Do_not_save: "Don't save";
            /** @constant */
            readonly selected_keywords_only: "selected keywords only";
            /** @constant */
            readonly Saved_list: "Saved list";
            /** @constant */
            readonly First_40_keywords: "First 40 keywords";
            /** @constant */
            readonly Save_list: "Save list";
            /** @constant */
            readonly Clear_list: "Clear list";
            /** @constant */
            readonly Highlight: "Highlight";
            /** @constant */
            readonly Hide_domains: "Gray out selected domains";
            /** @constant */
            readonly Hide_domains_comment: "Selected domains will be grayed out to make snapshots data reader-friendly and easy to analyze";
            /** @constant */
            readonly Highlighting_error: "Operation failed. Invalid domains: ";
            /** @constant */
            readonly Competitor_URLs: "Competitor URLs";
            /** @constant */
            readonly Add_to_competitors: "Add to competitors";
            /** @constant */
            readonly Remove_from_competitors: "Remove from competitors";
            /** @constant */
            readonly Added_competitors: "Added competitors";
            /** @constant */
            readonly Compare_all_keywords: "Compare all keywords";
            /** @constant */
            readonly Keyword_dynamics: "Keyword dynamics";
            /** @constant */
            readonly Select_keyword: "Select keyword";
            /** @constant */
            readonly Snippets_no_checked: "<b>Snippets in Snapshots</b> weren't collected on the selected dates.";
            /** @constant */
            readonly Snippets_no_checking: "<b>Snippets in Snapshots</b> aren't being collected. Turn this feature on in the project's settings.";
            /** @constant */
            readonly Snapshots_checks_in_progress_1: "You haven't collected snapshots for selected filters";
            /** @constant */
            readonly Snapshots_checks_in_progress_2: "Collect snapshots to see SERP TOPs for your keywords and your competitors' keywords.<br>Your keyword rankings will be checked when you collect snippets.<br>📊 <a href=\"/snapshots/\" target=\"_blank\">Why you need to check SERP Top →</a>";
            /** @constant */
            readonly Open_keyword_snapshot: "Open keyword snapshot";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
