/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Watcher": {
            /** @default Watcher settings */
            readonly Settings: string;
            /** @default {
             *       "http_codes": "HTTP Code",
             *       "title": "Title",
             *       "description": "Description",
             *       "h1": "H1 Header",
             *       "content": "Content"
             *     } */
            readonly menu: (string | number)[];
            /** @default Status */
            readonly Status_code: string;
            /** @default Without changes */
            readonly Without_changes: string;
            /** @default Full text */
            readonly Fulltext: string;
            /** @default With changes */
            readonly Only_with_changed: string;
            /** @default Track */
            readonly Header_start_short: string;
            /** @default Common settings */
            readonly Common_settings: string;
            /** @default Tracking */
            readonly Tracking: string;
            /** @default Cut &lt;script&gt; */
            readonly Cut_script: string;
            /** @default Scan method */
            readonly Scan_method: string;
            /** @default Text only / Cut tags */
            readonly Strip_tags: string;
            /** @default Change history:  */
            readonly Change_history: string;
            /** @default {
             *       "watcher_max_redirects": "",
             *       "watcher_user_agent": "User Agent can affect how the bot sees the site and how DDoS protection works.",
             *       "audit_page_delay": "",
             *       "audit_resource_delay": "",
             *       "audit_use_cookie": "Turn this feature on, if your DDoS protection uses cookies.<br><br>But it may cause more personalized information in checks and they could be distorted.",
             *       "server_location": "Change server location to access blocked websites.",
             *       "watcher_ignore_js": "",
             *       "watcher_types": {
             *         "title": "",
             *         "description": "",
             *         "h1": "",
             *         "content": ""
             *       },
             *       "watcher_strip_tags_from_result": ""
             *     } */
            readonly Hints_settings: (string | number)[];
            /** @default Add URLs to launch Watcher.<br>📡 <a href="/watcher/" target="_blank">How Website Watcher can help you →</a> */
            readonly Hint_not_urls_text: string;
            /** @default URLs */
            readonly Hint_not_urls_btn: string;
            /** @default You've never launched Watcher in this project.<br>📡 <a href="/watcher/" target="_blank">How Website Watcher can help you →</a> */
            readonly Hint_not_checks_text: string;
            /** @default Launch Watcher */
            readonly Hint_not_checks_btn: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
