/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Интерфейс настроек валюты
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=TV\Types\Config\Currency */
        "TV.Types.Config.Currency": {
            /**
             * Код валюты.
             * @default No set
             */
            readonly GA_CU: string;
            /**
             * Символ валюты.
             * @default No set
             */
            readonly CU_LABEL: string;
            /**
             * Префикс валюты.
             *
             *     `CU_PREFIX` и `getCUSuffix()` взаимоисключены, только один из них должен опредять не пустое значение
             * @default No set
             */
            readonly CU_PREFIX: string;
            /**
             * Иконка префикса валюты.
             * @default No set
             */
            readonly CU_PREFIX_ICO: string;
            /**
             * Иконка суффикса валюты.
             * @default No set
             */
            readonly CU_SUFFIX_ICO: string;
            /**
             * Точность округления для валюты.
             * @default 10000
             */
            readonly CU_PRECISION: number;
            /**
             * Стоимость проверки позиций.
             * @default 10000
             */
            readonly QUERY_COST: number;
            /**
             * Стоимость дополнительного конкурента.
             * @default 10000
             */
            readonly QUERY_COST_COMPETITORS: number;
            /**
             * Стоимость сбора сниппетов.
             * @default 10000
             */
            readonly QUERY_COST_SNIPPET: number;
            /**
             * Стоимость сбора снимка в проверке позиций.
             * @default 10000
             */
            readonly QUERY_COST_SNAPSHOT: number;
            /**
             * Коэффициент за проверку глубины.
             * @default 10000
             */
            readonly QUERY_COST_DEPTH_K: number;
            /**
             * Стоимость одного результата экспорта.
             * @default 10000
             */
            readonly EXPORT_ONE_RESULT_COST: number;
            /**
             * Проверка частоты запросов.
             * @default 10000
             */
            readonly QUERY_COST_FREQUENCY: number;
            /**
             * Сбор ядра.
             * @default 10000
             */
            readonly SY_COST: number;
            /**
             * Сбор подсказок в поиске, за 1, 2 и 3 глубину
             * @default [
             *       10000,
             *       10000,
             *       10000
             *     ]
             */
            readonly SY_HINTS_COST: unknown[];
            /**
             * Корректировка ставок.
             * @default 10000
             */
            readonly BROKER_COST: number;
            /**
             * Необходимый баланс для запуска корректировки ставок.
             * @default 10000
             */
            readonly BROKER_MIN_BALANCE: number;
            /**
             * Стоимость кластеризации.
             * @default 10000
             */
            readonly CLASTER_COST: number;
            /**
             * Стоимость кластеризации от 10 000 запросов.
             * @default 10000
             */
            readonly CLASTER_COST_10: number;
            /**
             * Стоимость кластеризации от 50 000 запросов.
             * @default 10000
             */
            readonly CLASTER_COST_50: number;
            /**
             * Стоимость кластеризации от 250 000 запросов.
             * @default 10000
             */
            readonly CLASTER_COST_250: number;
            /**
             * Стоимость перекластеризации.
             * @default 10000
             */
            readonly CLASTER_CHANGE_COST: number;
            /**
             * Генерации карты сайта до 100 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_100: number;
            /**
             * Генерации карты сайта до 1000 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_1000: number;
            /**
             * Генерации карты сайта до 10 000 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_10000: number;
            /**
             * Генерации карты сайта до 100 000 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_100000: number;
            /**
             * Генерации карты сайта до 150 000 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_150000: number;
            /**
             * Генерации карты сайта до 300 000 страниц.
             * @default 10000
             */
            readonly AUDIT_SITEMAP_300000: number;
            /**
             * Стоимость аудита.
             * @default 10000
             */
            readonly AUDIT_COST: number;
            /**
             * Стоимость аудита от 100 страниц.
             * @default 10000
             */
            readonly AUDIT_COST_100: number;
            /**
             * Стоимость аудита от 1000 страниц.
             * @default 10000
             */
            readonly AUDIT_COST_1000: number;
            /**
             * Стоимость аудита от 10 000 страниц.
             * @default 10000
             */
            readonly AUDIT_COST_10000: number;
            /**
             * Стоимость радара.
             * @default 10000
             */
            readonly WATCHER_COST: number;
            /**
             * Стоимость индексации.
             * @default 10000
             */
            readonly INDEXING_COST: number;
            /**
             * Стоимость упоминатора.
             * @default 10000
             */
            readonly MENTIONS_COST: number;
            /**
             * Стоимость анализа конкурентов.
             * @default 10000
             */
            readonly COMPETITORS_COST: number;
            /**
             * Стоимость веб-скриншотов.
             * @default 10000
             */
            readonly WEB_SCREENS_COST: number;
            /**
             * Список тарифных планов.
             * @default [
             *       "No set",
             *       "No set",
             *       "No set",
             *       "No set",
             *       "No set"
             *     ]
             */
            readonly TARIFF_NAMES: unknown[];
            /**
             * Список стоимости тарифов.
             * @default [
             *       10000,
             *       10000,
             *       10000,
             *       10000,
             *       10000
             *     ]
             */
            readonly TARIFF_VALUES: unknown[];
            /**
             * Список скидок по тарифам.
             * @default [
             *       0,
             *       10,
             *       15,
             *       20,
             *       30
             *     ]
             */
            readonly TARIFF_DISCOUNT: unknown[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
