/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Ai.Tracker": {
            /** @constant */
            readonly English: "English";
            /** @constant */
            readonly Russian: "Russian";
            /** @constant */
            readonly Ai_tracker_bank_info: "Checking for mentions in neural networks";
            /** @constant */
            readonly Add_brand_info: "Добавьте сведения о своём бренде, чтобы запустить анализ.<br> <a href=\"/support/rankings/se/\" target=\"_blank\">Как настроить AI-трекер →</a>";
            /** @constant */
            readonly Model_Yandex_Alice: "Yandex Alice";
            /** @constant */
            readonly First_you_need_to_enter_the_brand_name: "First you need to enter the brand name";
            /** @constant */
            readonly Brand_information: "Brand information";
            /** @constant */
            readonly Brand_name: "Brand name";
            /** @constant */
            readonly Alternative_spellings_for_the_brand_and_website: "Alternative spellings for the brand and website";
            /** @constant */
            readonly Enter_alternative_brand_names: "Enter alternative brand names. Each on a new line";
            /** @constant */
            readonly Context_setting: "Context setting";
            /** @constant */
            readonly System_prompt: "System prompt";
            /** @constant */
            readonly Enter_additional_information_to_help_you_fine_tune_the_context: "Enter additional information to help you fine-tune the context.";
            /** @constant */
            readonly Automatic_pick_up_of_alternative_brand_spellings: "Automatic pick up of alternative brand spellings";
            /** @constant */
            readonly Launch_AI_analysis: "Launch AI analysis";
            /** @constant */
            readonly Launching_AI_analysis: "Launching AI analysis";
            /** @constant */
            readonly Cost_of_analysis: "Cost of analysis";
            /** @constant */
            readonly Make_prompts: "Make prompts";
            /** @constant */
            readonly Selecting_neural_networks: "Selecting neural networks";
            /** @constant */
            readonly Add_prompts: "Add prompts";
            /** @constant */
            readonly Select_neural_networks: "Select neural networks";
            /** @constant */
            readonly No_data_in_day: "В выбранный день данные не анализировались.<br> <a href=\"/support/rankings/se/\" target=\"_blank\">Как работает AI-трекер →</a>";
            /** @constant */
            readonly Add_neural_networks: "Выберите нейросети, чтобы запустить анализ.";
            /** @constant */
            readonly Add_prompts_to_go: "Добавьте промпты, чтобы запустить анализ.";
            /** @constant */
            readonly Settings: "AI-tracker settings";
            /** @constant */
            readonly Ai_analysis: "AI-анализ";
            /** @constant */
            readonly Analysis_go: "Запустить анализ";
            /** @constant */
            readonly Prompts: "Prompts";
            /** @constant */
            readonly Search_prompts: "Поиск по промптам";
            /** @constant */
            readonly Neural_network: "Neural network";
            /** @constant */
            readonly Remove_prompt: "Вы действительно хотите удалить этот промпт?";
            /** @constant */
            readonly Sort_mentioned: "Сортировка по упоминанию";
            /** @constant */
            readonly Sort_tone: "Сортировка по тональности";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
