/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Ai.Tracker": {
            /** @constant */
            readonly English: "English";
            /** @constant */
            readonly Russian: "Russian";
            /** @constant */
            readonly Ai_tracker_bank_info: "Checking for mentions in AI";
            /** @constant */
            readonly Add_brand_info: "Add your brand to launch check.<br>💼 <a href=\"/support/ai-tracker/\" target=\"_blank\">How to add brand →</a>";
            /** @constant */
            readonly Model_Yandex_Alice: "Yandex Alice";
            /** @constant */
            readonly First_you_need_to_enter_the_brand_name: "First you need to enter the brand name";
            /** @constant */
            readonly Brand_information: "Brand information";
            /** @constant */
            readonly Brand_name: "Brand name";
            /** @constant */
            readonly Alternative_spellings_for_the_brand_and_website: "Alternative spellings for the brand and website";
            /** @constant */
            readonly Enter_alternative_brand_names: "Enter alternative brand names. Each on a new line";
            /** @constant */
            readonly Context_setting: "Context setting";
            /** @constant */
            readonly System_prompt: "System prompt";
            /** @constant */
            readonly Enter_additional_information_to_help_you_fine_tune_the_context: "Enter additional information to help you fine-tune the context.";
            /** @constant */
            readonly Automatic_pick_up_of_alternative_brand_spellings: "Automatic pick up of alternative brand spellings";
            /** @constant */
            readonly Launch_AI_analysis: "Launch AI analysis";
            /** @constant */
            readonly Launching_AI_analysis: "Launching AI analysis";
            /** @constant */
            readonly Cost_of_analysis: "Cost of analysis";
            /** @constant */
            readonly Make_prompts: "Make prompts";
            /** @constant */
            readonly Selecting_neural_networks: "Selecting neural networks";
            /** @constant */
            readonly Add_prompts: "Add prompts";
            /** @constant */
            readonly Add_prompts_2: "Add prompts";
            /** @constant */
            readonly Select_neural_networks: "Select neural networks";
            /** @constant */
            readonly No_data_in_day: "There are no checks in the picked period.<br>🛠️ <a href=\"/support/ai-tracker/\" target=\"_blank\">How AI Tracker works →</a> and 🎯 <a href=\"/ai-tracker/\" target=\"_blank\">Why you need to check mentions in AI</a>";
            /** @constant */
            readonly Add_neural_networks: "Pick AIs to launch analysis.<br>✨ <a href=\"/support/ai-tracker/\" target=\"_blank\">How to add AIs →</a>";
            /** @constant */
            readonly Add_prompts_to_go: "Add prompts to launch analysis.<br>🔑 <a href=\"/support/ai-tracker/\" target=\"_blank\">How to add prompts →</a>";
            /** @constant */
            readonly Settings: "AI Tracker settings";
            /** @constant */
            readonly Ai_analysis: "AI analysis";
            /** @constant */
            readonly Analysis_go: "Launch analysis";
            /** @constant */
            readonly Prompts: "Prompts";
            /** @constant */
            readonly Prompt: "Prompt";
            /** @constant */
            readonly Search_prompts: "Prompt search";
            /** @constant */
            readonly Neural_network: "Neural network";
            /** @constant */
            readonly Remove_prompt: "Are you sure you want to delete this prompt?";
            /** @constant */
            readonly Sort_mentioned: "Sorting by mentions";
            /** @constant */
            readonly Sort_sentiment: "Sorting by tone";
            /** @constant */
            readonly Prompts_can_be_deleted_and_restored_within_the_same_group: "Prompts can be deleted/restored within the same group";
            /** @constant */
            readonly Autogeneration_of_prompts: "Autogeneration of prompts";
            /** @constant */
            readonly Type_of_activity: "Type of activity";
            /** @constant */
            readonly Enter_the_activities: "Enter the activities of the brand or website. This will help fine-tune the context and select prompts.";
            /** @constant */
            readonly Prompt_length: "Prompt length";
            /** @constant */
            readonly Number_of_prompts: "Number of prompts";
            /** @constant */
            readonly Short: "Short";
            /** @constant */
            readonly Medium: "Medium";
            /** @constant */
            readonly Long: "Long";
            /** @constant */
            readonly Add_prompts_for_checking: "Please add prompts for checking";
            /** @constant */
            readonly Added: "Added prompts";
            /** @constant */
            readonly Missed: "Skipped duplicate prompts";
            /** @constant */
            readonly Neuro_answer: "Neuro answer";
            /** @constant */
            readonly Answer_from: "Answer from";
            /** @constant */
            readonly Analysis_was_not_performed: "Analysis was not performed";
            /** @constant */
            readonly Mentions: "Mentions";
            /** @constant */
            readonly Check_need_config: "To launch the AI-tracker, you need to configure the list of tested prompts and select neural networks.";
            /** @constant */
            readonly Already_started: "AI-tracker already started";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
