/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Проверить код для подтверждения действия */
        "Sms_2.Methods.CheckPIN.Get": {
            /** Код подтверждения */
            pin: string;
            /**
             * Телефон/массив или строка(через запятую) телефонов, на которые надо отправить код подтверждения
             * @description @type string | array
             */
            phones?: unknown;
        };
        /** @throws Exception */
        "Sms_2.Methods.CheckPIN.Get.Exec": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
