/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Projects.CheckButton": {
            /** @default Check Rankings */
            readonly Check_positions: string;
            /** @default Run Audit */
            readonly Check_audit: string;
            /** @default Track changes */
            readonly Check_watcher: string;
            /** @default Check indexing */
            readonly Check_indexing: string;
            /** @default Generate sitemap */
            readonly Check_sitemap: string;
            /** @default Last check */
            readonly Last_check: string;
            /** @default In queue */
            readonly In_queue: string;
            /** @default In progress */
            readonly In_work: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
