/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=I18n\Projects\Settings\En */
        "I18n.Projects.Settings": {
            /** @constant */
            readonly Change_project_owner_description: "Change of project owner is a procedure that results in the change of the Project Owner in the service. Write-offs of funds for services provided by the service as a result of one actions or another will be made on behalf of the new owner. All operations with the project, including restoration of access to it if necessary, will be possible only on behalf of the new person.";
            /** @constant */
            readonly Transfer_control_over_project: "To transfer control over a project, enter the user's email in the form below and click";
            /** @constant */
            readonly Region_depth_adaptive: "Dynamic parse depth";
            /** @constant */
            readonly Region_depth_adaptive_hint: "<b>Dynamic parse depth</b>\n\t<ul>\n\t\t<li>If website is ranked in Top and there's no need to parse the next SERP page, it will be skipped automatically.</li>\n\t\t<li>The cost of skipped SERPs is charged back to your account the next day.</li>\n\t</ul>\n\tE.g.: if website is ranked in Top-10, and you've picked Top-30, you'be charged only for Top-10. Tap question mark icon to learn more about the algorythm.";
            /** @constant */
            readonly Google_drive: "Google drive";
            /** @constant */
            readonly Token_is_active_until: "Token is active until";
            /** @constant */
            readonly Reconnect: "Reconnect";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
