/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование статуса IP */
        "Robot_2.Methods.Admin.Keys.Status.Edit": {
            /** ID слоя */
            layer_id: number;
            /** Ключ ПС */
            searcher_key: number;
            /** Домен */
            status: string;
            /**
             * Количество объектов, которые необходимо получить в результате
             *
             *     Используется в паре с offset
             */
            limit?: number | null;
        };
        "Robot_2.Methods.Admin.Keys.Status.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
