/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Apometr.History": {
            time?: unknown;
            action?: unknown;
            region_index?: unknown;
            keyword_id?: unknown;
            url?: unknown;
            position?: unknown;
            d?: unknown;
            d_day?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
