/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отправка проектов на проверку индексации */
        "Audit_2.Methods.Indexing.Checker.Go.Edit": {
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
        };
        /** Список id проектов, отправленных на проверку */
        "Audit_2.Methods.Indexing.Checker.Go.Edit.Exec": {
            projectIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
