/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получить подсазки запросов для добавления в проект
         *
         *     Доступ по API закрыт
         */
        "Projects_2.Methods.Master.HintsKeywords.Get": {
            /** ID проекта */
            project_id: number;
            /** Делать ли проверку на наличие пути в URL */
            strict_query?: boolean;
            /** Ключевая фраза (или ее часть) для сравнения запросов */
            query_vs?: string | null;
            /**
             * Тип связи запросов между конкурентами
             * @default me
             */
            rel_vs?: import('../../../../Competitors_2/Types/ByUrl/Table/Keywords/TypeVS.ts').components['schemas']['Competitors_2.Types.ByUrl.Table.Keywords.TypeVS'];
            /** Минимальная схожесть */
            intersection?: number;
        };
        "Projects_2.Methods.Master.HintsKeywords.Get.Exec": unknown[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
