/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Категория данных
         * @enum {string}
         */
        "System_2.Types.Properties.Property.TargetName": System_2TypesPropertiesPropertyTargetName;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum System_2TypesPropertiesPropertyTargetName {
    // Проекты
    ModProjects = "mod_projects"
}
export type operations = Record<string, never>;
