/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение заархивированного приложения
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\App_2\Methods\Get
         */
        "App_2.Methods.Get": Record<string, never>;
        "App_2.Methods.Get.Exec": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
