/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Broker_2\Methods\Groups\Add */
        "Broker_2.Methods.Groups.Add": {
            /** Id кампании */
            campaign_tv_id: number;
            /** Имена групп */
            groups_names: unknown[];
        };
        /** выводит int, если функция провайдера не определена */
        "Broker_2.Methods.Groups.Add.Exec": (unknown[] | number | null) | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
