/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Типы метода перебора
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Keywords_2\Types\Collect\HintGenerators
         * @description @extends API\Types\AbstractObjectArray<HintGenerator>
         *     @method HintGenerator[] getValues()
         *     @method HintGenerator current()
         *     @see HintGenerator
         */
        "Keywords_2.Types.Collect.HintGenerators": import('./HintGenerator.ts').components['schemas']['Keywords_2.Types.Collect.HintGenerator'][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
