/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Определитель с настройками для подбора */
        "Keywords_2.Types.Collect.Qualifier": {
            region_key: number;
            searcher_key: components["schemas"]["Keywords_2.Types.Collect.SearcherKey"];
            region_lang?: string | null;
            also_searched?: boolean | null;
            depth?: number | null;
            hint_depth?: number | null;
            hint_generators?: components["schemas"]["Keywords_2.Types.Collect.HintGenerators"] | null;
        };
        /**
         * Ключ поисковой системы для проверки частоты
         * @enum {integer}
         */
        "Keywords_2.Types.Collect.SearcherKey": 0 | 1 | 5 | 104 | 100 | 101 | 105;
        /**
         * Тип метода перебора
         * @enum {string}
         */
        "Keywords_2.Types.Collect.HintGenerator": "letter" | "letter_ru" | "number" | "space";
        /** Типы метода перебора */
        "Keywords_2.Types.Collect.HintGenerators": components["schemas"]["Keywords_2.Types.Collect.HintGenerator"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
