/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Определитель с настройками для подбора */
        "Keywords_2.Types.Collect.Qualifier": {
            region_key: number;
            searcher_key: import('./SearcherKey.ts').components['schemas']['Keywords_2.Types.Collect.SearcherKey'];
            region_lang?: string | null;
            also_searched?: boolean | null;
            depth?: number | null;
            hint_depth?: number | null;
            hint_generators?: import('./HintGenerators.ts').components['schemas']['Keywords_2.Types.Collect.HintGenerators'] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
