/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Создание сертификата
         *
         *     Можно создавать только для пройденных курсов */
        "Content_2.Methods.Journal.Course.Certificates.Add": {
            /** Url курса относительно домена */
            course_url: string;
            /** Имя на кого выписывается сертификат */
            user_name: string;
        };
        /** @throws Exception */
        "Content_2.Methods.Journal.Course.Certificates.Add.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
