/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавление счета на оплату */
        "Admin_2.Methods.Accounting.Invoices.Add": {
            /** Дата документа */
            document_date: components["schemas"]["TV.API.Types.Date"];
            /** Номер документа */
            document_number: string;
            /** Имя файла */
            file_name: string;
            /** Данные файла */
            file_data: string;
            /** Имя организации */
            org_name: string;
            /** ИНН */
            inn: string;
            /** Сумма */
            sum: number;
        };
        /**
         * Дата
         * @example 2000-01-01
         */
        "TV.API.Types.Date": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
