/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение админской ссылки к тикетам. Только для админов */
        "Tickets_2.Methods.Admin.Ticket.ResourceAdmin.Edit": {
            /** Ссылка */
            resource_admin: string;
            /** ID тикета */
            ticket_id: number;
        };
        "Tickets_2.Methods.Admin.Ticket.ResourceAdmin.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
