/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение токена авторизации для работы с safari web push
         *
         *     Создаст токен, если его не существует
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Informer_2\Methods\Push\Safari\WebService\AuthToken\Get
         */
        "Informer_2.Methods.Push.Safari.WebService.AuthToken.Get": Record<string, never>;
        "Informer_2.Methods.Push.Safari.WebService.AuthToken.Get.Exec": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
