/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Параметры для отчетов с базисом по дате
         *
         *     Используется в отчетах, где ключевым параметром является дата проверки
         * @description @see class/API/Params/History/README.md
         *     @mixin API\Method\AbstractGet
         */
        "TV.API.Params.History.DateRangeTrait": {
            /**
             * Произвольные даты без использования диапазона
             *
             *     Необходимо указать либо `date1`, `date2`, `type_range`, либо `dates` (вместе указывать нельзя)
             */
            dates?: import('../../Types/DateArray.ts').components['schemas']['TV.API.Types.DateArray'] | null;
            /**
             * Тип диапазона дат
             * @default 2
             */
            type_range: import('../../Types/History/TypeRange.ts').components['schemas']['TV.API.Types.History.TypeRange'];
            /**
             * Дата начала диапазона
             *
             *     Используется вместе с date2 для задания диапазона дат
             */
            date1?: import('../../Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Дата окончания диапазона
             *
             *     Используется вместе с date1 для задания диапазона дат
             */
            date2?: import('../../Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Количество дат в диапазоне
             *
             *     Максимальное значение ограничивается константой MAX_DATES конкретного модуля
             *
             *     Работает совместно с `type_range`
             * @default 31
             */
            count_dates: number;
            /**
             * Период в днях
             *
             *     Используется для алгоритма получения дат через равные промежутки (`type_range` = 6)
             *
             *     Не более 31
             * @default 7
             */
            period_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
