/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Landings.Championship": {
            /** @default Best cases */
            Best_cases: string;
            /** @default Main competition 🏆 */
            Main_competition: string;
            /** @default Special nominations 🏆 */
            Special_nominations: string;
            /** @default Nomination */
            Nomination: string;
            /** @default Place */
            Place: string;
            /** @default Case and author */
            Case_and_author: string;
            /** @default place */
            place: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
