/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "I18n.Landings.Promocode": {
            /** @constant */
            readonly Title?: "Enter promocode to get bonus - Topvisor";
            /** @constant */
            readonly Description: "Here you can enter a promocode and get a bonus. You can get a promocode via mailing, social networks or in person on conferences where we take part.";
            /** @constant */
            readonly OpenGraph_title: "Enter promocode";
            /** @constant */
            readonly OpenGraph_description?: "And get bonus on Topvisor";
            /** @constant */
            readonly Enter_promocode: "Enter promocode";
            /** @constant */
            readonly Promocode: "Promocode";
            /** @constant */
            readonly Info_title: "Hey — you've got a luck potion";
            /** @constant */
            readonly Info_description?: "If you sign up at this page, your starting bonus in Topvisor will be 100 rubles.";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
