/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение сводки числа рефералов по своему уровню */
        "Admin_2.Methods.Affiliate.ReferralsByLevel.Get": {
            /** Год для сводки */
            year: number;
            /** Валюта реферало */
            currency: components["schemas"]["TV.API.Types.Currency"];
        };
        /**
         * Валюта
         *
         *     Этот общий тип, не зависящий от контекста
         *
         *     Дополниетольно нужно проверять в API методах через site()->checkAllowCurrency() в функции check()
         * @enum {string}
         */
        "TV.API.Types.Currency": "RUB" | "USD";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
