/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.BalanceHistory": {
            "COUNT(*)"?: any;
            "TOTAL()"?: any;
            currency?: any;
            plus?: any;
            sum_group?: any;
            user_id?: number | null;
            by_user_id?: any;
            sum?: any;
            type?: any;
            info?: any;
            target?: any;
            target_id?: number | null;
            date?: any;
            project_name?: any;
            project_tags?: any;
            project_folder_id?: any;
            by_user_email?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
