/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Groups": {
            "COUNT(*)"?: unknown;
            id?: unknown;
            project_id?: unknown;
            folder_id?: unknown;
            name?: unknown;
            on?: unknown;
            status?: unknown;
            ord?: unknown;
            folder_path?: unknown;
            folder_ord?: unknown;
            count_keywords?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "region_key",
             *         "searcher_key",
             *         "type"
             *       ]
             *     } */
            volume?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "date",
             *         "project_id",
             *         "region_index"
             *       ]
             *     } */
            "POSITIONS_AVG()"?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "date",
             *         "project_id",
             *         "region_index"
             *       ]
             *     } */
            "POSITIONS_TOP10()"?: unknown;
            /** @example {
             *       "need set qualifiers": [
             *         "date",
             *         "project_id",
             *         "region_index"
             *       ]
             *     } */
            "POSITIONS_VISIBILITY()"?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
