/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Annotations": import('./Annotations.ts').components['schemas']['Models.Annotations'];
        "Models.BalanceHistory": import('./BalanceHistory.ts').components['schemas']['Models.BalanceHistory'];
        "Models.Comments": import('./Comments.ts').components['schemas']['Models.Comments'];
        "Models.ContentsRedirects": import('./ContentsRedirects.ts').components['schemas']['Models.ContentsRedirects'];
        "Models.CronCommands": import('./CronCommands.ts').components['schemas']['Models.CronCommands'];
        "Models.EmptyModel": import('./EmptyModel.ts').components['schemas']['Models.EmptyModel'];
        "Models.Folders": import('./Folders.ts').components['schemas']['Models.Folders'];
        "Models.Groups": import('./Groups.ts').components['schemas']['Models.Groups'];
        "Models.Keywords": import('./Keywords.ts').components['schemas']['Models.Keywords'];
        "Models.Magnet": import('./Magnet.ts').components['schemas']['Models.Magnet'];
        "Models.Model": import('./Model.ts').components['schemas']['Models.Model'];
        "Models.Pages": import('./Pages.ts').components['schemas']['Models.Pages'];
        "Models.Payments": import('./Payments.ts').components['schemas']['Models.Payments'];
        "Models.Projects": import('./Projects.ts').components['schemas']['Models.Projects'];
        "Models.Quizes": import('./Quizes.ts').components['schemas']['Models.Quizes'];
        "Models.Requisites": import('./Requisites.ts').components['schemas']['Models.Requisites'];
        "Models.ShortLink": import('./ShortLink.ts').components['schemas']['Models.ShortLink'];
        "Models.Tickets": import('./Tickets.ts').components['schemas']['Models.Tickets'];
        "Models.Urls": import('./Urls.ts').components['schemas']['Models.Urls'];
        "Models.Votes": import('./Votes.ts').components['schemas']['Models.Votes'];
        "Models.Admin.Invoices": import('./Admin/Invoices.ts').components['schemas']['Models.Admin.Invoices'];
        "Models.Admin.Staff": import('./Admin/Staff.ts').components['schemas']['Models.Admin.Staff'];
        "Models.Admin.Users": import('./Admin/Users.ts').components['schemas']['Models.Admin.Users'];
        "Models.Analytics.Events": import('./Analytics/Events.ts').components['schemas']['Models.Analytics.Events'];
        "Models.Analytics.Ranks": import('./Analytics/Ranks.ts').components['schemas']['Models.Analytics.Ranks'];
        "Models.Analytics.RanksUsers": import('./Analytics/RanksUsers.ts').components['schemas']['Models.Analytics.RanksUsers'];
        "Models.Audit.Checks": import('./Audit/Checks.ts').components['schemas']['Models.Audit.Checks'];
        "Models.Audit.Css": import('./Audit/Css.ts').components['schemas']['Models.Audit.Css'];
        "Models.Audit.Images": import('./Audit/Images.ts').components['schemas']['Models.Audit.Images'];
        "Models.Audit.Js": import('./Audit/Js.ts').components['schemas']['Models.Audit.Js'];
        "Models.Audit.Links": import('./Audit/Links.ts').components['schemas']['Models.Audit.Links'];
        "Models.Audit.Pages": import('./Audit/Pages.ts').components['schemas']['Models.Audit.Pages'];
        "Models.Broker.Ads": import('./Broker/Ads.ts').components['schemas']['Models.Broker.Ads'];
        "Models.Broker.Campaigns": import('./Broker/Campaigns.ts').components['schemas']['Models.Broker.Campaigns'];
        "Models.Broker.Groups": import('./Broker/Groups.ts').components['schemas']['Models.Broker.Groups'];
        "Models.Broker.Keywords": import('./Broker/Keywords.ts').components['schemas']['Models.Broker.Keywords'];
        "Models.Broker.Log": import('./Broker/Log.ts').components['schemas']['Models.Broker.Log'];
        "Models.Competitors.Domains": import('./Competitors/Domains.ts').components['schemas']['Models.Competitors.Domains'];
        "Models.Competitors.Keywords": import('./Competitors/Keywords.ts').components['schemas']['Models.Competitors.Keywords'];
        "Models.Competitors.Urls": import('./Competitors/Urls.ts').components['schemas']['Models.Competitors.Urls'];
        "Models.Competitors.Wordstat": import('./Competitors/Wordstat.ts').components['schemas']['Models.Competitors.Wordstat'];
        "Models.Magnet.Ganalytics": import('./Magnet/Ganalytics.ts').components['schemas']['Models.Magnet.Ganalytics'];
        "Models.Magnet.Gsc": import('./Magnet/Gsc.ts').components['schemas']['Models.Magnet.Gsc'];
        "Models.Magnet.Metrika": import('./Magnet/Metrika.ts').components['schemas']['Models.Magnet.Metrika'];
        "Models.Magnet.Webmaster": import('./Magnet/Webmaster.ts').components['schemas']['Models.Magnet.Webmaster'];
        "Models.Mentions.Mentions": import('./Mentions/Mentions.ts').components['schemas']['Models.Mentions.Mentions'];
        "Models.Mentions.Rules": import('./Mentions/Rules.ts').components['schemas']['Models.Mentions.Rules'];
        "Models.Mentions.Searchers": import('./Mentions/Searchers.ts').components['schemas']['Models.Mentions.Searchers'];
        "Models.Quizes.Questions": import('./Quizes/Questions.ts').components['schemas']['Models.Quizes.Questions'];
        "Models.Users.Ranks": import('./Users/Ranks.ts').components['schemas']['Models.Users.Ranks'];
        "Models.Users.Referrals": import('./Users/Referrals.ts').components['schemas']['Models.Users.Referrals'];
        "Models.Users.Verif": import('./Users/Verif.ts').components['schemas']['Models.Users.Verif'];
        "Models.Watcher.Results": import('./Watcher/Results.ts').components['schemas']['Models.Watcher.Results'];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
