/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Payments": {
            "COUNT(*)"?: any;
            "HAS_DOC()"?: any;
            id?: any;
            external_id?: any;
            user_id?: any;
            system?: any;
            requisites_id?: any;
            data?: any;
            items?: any;
            sum?: any;
            currency?: any;
            status?: any;
            recurrent_type?: any;
            tariff_id?: any;
            tariff_count_month?: any;
            subscription_plan_id?: any;
            subscription_cycle?: any;
            date?: any;
            date_month?: any;
            date_finished?: any;
            date_month_finished?: any;
            fromBase64Data?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
