/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Projects": {
            "COUNT(*)"?: unknown;
            "IS_YOUTUBE()"?: unknown;
            "IS_APP_STORE()"?: unknown;
            "IS_GOOGLE_PLAY()"?: unknown;
            "GEN_SEARCH_STRING()"?: unknown;
            id?: unknown;
            user_id?: unknown;
            name?: string | null;
            url?: unknown;
            date?: unknown;
            last_view?: unknown;
            folder_id?: number | null;
            folder_name?: unknown;
            task_time_delete?: unknown;
            task_method_name?: unknown;
            task_method_params_json?: unknown;
            site?: unknown;
            update?: unknown;
            status_positions?: string | null;
            positions_time?: unknown;
            positions_date?: unknown;
            positions_percent?: unknown;
            status_positions_time?: unknown;
            status_positions_date?: unknown;
            status_positions_percent?: unknown;
            status_positions_by_keywords?: unknown;
            status_volumes?: unknown;
            status_claster?: unknown;
            status_audit?: unknown;
            status_audit_time?: unknown;
            status_audit_percent?: unknown;
            status_watcher?: unknown;
            status_watcher_percent?: unknown;
            status_indexing?: unknown;
            status_indexing_percent?: unknown;
            status_sitemap?: unknown;
            status_sitemap_percent?: unknown;
            status_urlsUpdater?: unknown;
            on?: unknown;
            subdomains?: unknown;
            filter?: unknown;
            auto_correct?: unknown;
            with_snippets?: unknown;
            do_snapshots?: unknown;
            do_snapshots_with_snippets?: unknown;
            report_last_time?: unknown;
            common_traffic?: unknown;
            guest_link_right?: unknown;
            is_task?: unknown;
            count_keywords?: unknown;
            right?: unknown;
            ord?: unknown;
            favorite?: unknown;
            tags?: unknown;
            user_email?: unknown;
            user_currency?: unknown;
            broker_count_campaigns?: unknown;
            broker_count_banners?: unknown;
            broker_count_banners_off?: unknown;
            domain_expire?: unknown;
            ssl_expire?: unknown;
            competitor?: unknown;
            competitor_ord?: unknown;
            pos_summary_up?: unknown;
            pos_summary_stay?: unknown;
            pos_summary_down?: unknown;
            pos_summary_avg?: unknown;
            pos_summary_visibility?: unknown;
            audit_server_location?: unknown;
            audit_auto_collect_pages?: number | null;
            audit_auto_collect_pages_limit?: number | null;
            indexing_searchers_keys?: (string | number)[] | null;
            watcher_types?: (string | number)[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
