/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Tickets": {
            "REQUISITES()"?: any;
            "LAST_MESSAGE_TEXT()"?: any;
            "LAST_MESSAGE_USER_ID()"?: any;
            "READED(0)"?: any;
            "READED(1)"?: any;
            id?: any;
            user_id?: any;
            social_user_id?: any;
            type?: any;
            text?: any;
            create?: any;
            time?: any;
            status?: any;
            lang?: any;
            email?: any;
            user_data?: any;
            manager_id?: any;
            owner_readed?: any;
            answerer_readed?: any;
            admin_writing?: any;
            task_id?: any;
            tags?: any;
            rate?: any;
            rate_comment?: any;
            rate_time?: any;
            admin_comment?: any;
            "VS_USER_IS_ONLINE()"?: any;
            vs_user_name?: any;
            vs_user_email?: any;
            vs_user_avatar?: any;
            vs_user_lastactive?: any;
            social_nickname?: any;
            social_network?: any;
            social_last_message_time?: any;
            social_name?: any;
            social_type?: any;
            social_post_id?: any;
            social_reply_to_id?: any;
            message_id?: any;
            message_user_id?: any;
            message_text?: any;
            message_data?: any;
            message_files?: any;
            message_time?: any;
            message_noticed?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
