/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Votes": {
            id?: any;
            site?: any;
            subdomain?: any;
            url?: any;
            user_id?: any;
            rate?: any;
            created_time?: any;
            comment?: any;
            is_viewed?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
