/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Редактирование параметра
         *
         *     Не хранить в параметрах конфиденциальную информацию
         */
        "System_2.Methods.Properties.Property.Edit": {
            /** Имя параметра */
            name: string;
            /** Значение параметра */
            value?: unknown;
            /** @default varchar */
            type?: import('../../../Types/Properties/Property/Type.ts').components['schemas']['System_2.Types.Properties.Property.Type'];
            /** Кодировать ли данные в base64 */
            encode_to_base64?: boolean;
            target_name?: import('../../../Types/Properties/Property/TargetName.ts').components['schemas']['System_2.Types.Properties.Property.TargetName'] | null;
            /** Id объекта в категории */
            target_id?: number;
        };
        "System_2.Methods.Properties.Property.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
