/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавление запроса */
        "KeywordsAi_2.Methods.Keywords.Add": {
            /** Ключевая фраза */
            name: string;
            /** Вставить к указанному объекту
             *
             *     Если в to_type указано "Перед или после запроса", то принимает id запроса
             *     Если в to_type указано "В конец или начало группы", то принимает id группы */
            to_id: number;
            /** @default in_group */
            to_type?: import('../../../Keywords_2/Types/Keywords/ToType.ts').components['schemas']['Keywords_2.Types.Keywords.ToType'];
            /** Теги запроса */
            tags?: import('../../../Tags_2/Types/TagsIds.ts').components['schemas']['Tags_2.Types.TagsIds'] | null;
            /** Целевая страница для запроса */
            target?: import('../../../TV/API/Types/Url.ts').components['schemas']['TV.API.Types.Url'] | null;
            /** Удалить дубликаты */
            move_duplicate?: boolean;
            /** Имя группы для перемещения дубликатов
             *
             *     Работает вместе с move_duplicate */
            move_duplicate_group_name?: string;
            project_id: import('../../../TV/API/Params/ProjectIdTrait.ts').components['schemas']['TV.API.Params.ProjectIdTrait']['project_id'];
            fields?: import('../../../TV/API/Params/FieldsTrait.ts').components['schemas']['TV.API.Params.FieldsTrait']['fields'];
        };
        "KeywordsAi_2.Methods.Keywords.Add.Exec": unknown[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
