/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Модель нейросети для AI-трекера
         * @description @extends API\Types\AbstractTypedArray<ModelName>
         *     @method ModelName[] getValues()
         *     @method ModelName current()
         *     @see ModelName
         */
        "AiTracker_2.Types.ModelsNames": import('./ModelName.ts').components['schemas']['AiTracker_2.Types.ModelName'][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
