/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Право для гостевых ссылок
         * @enum {string}
         */
        "Positions_2.Types.Settings.GuestLinkRight": Positions_2TypesSettingsGuestLinkRight;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Positions_2TypesSettingsGuestLinkRight {
    // Частота запросов
    Volume = "volume",
    // Частота запросов
    Frequency = "frequency",
    // Трафик
    Visitors = "visitors",
    // Выбор дат
    Dates = "dates",
    // Сводка
    Summary = "summary",
    // Расширенная сводка
    Graphics = "graphics",
    // Конкуренты
    Competitors = "competitors"
}
export type operations = Record<string, never>;
