/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавление задачи cron */
        "Cron_2.Methods.Commands.Add": {
            /** Описание задачи */
            description: string;
            days: components["schemas"]["Cron_2.Types.Days"];
            hh: components["schemas"]["Cron_2.Types.Hour"];
            i: components["schemas"]["Cron_2.Types.Minute"];
            /** Статус активности задачи */
            on: boolean;
            command: components["schemas"]["command"];
        };
        /**
         * День недели, в который должен производиться запуск cron
         * @enum {string}
         */
        "Cron_2.Types.Day": "1" | "2" | "3" | "4" | "5" | "6" | "7";
        /** Дни недели, в которые должен производиться запуск cron */
        "Cron_2.Types.Days": components["schemas"]["Cron_2.Types.Day"][];
        /**
         * Час в который должен производиться запуск cron
         * @description Пустое значение зарезервированно для запуска cron каждый час
         *
         *     Значение должно находиться в диапазоне от 0 до 23 включительно
         */
        "Cron_2.Types.Hour": string;
        /**
         * Минута или интервал в минутах в который должен производиться запуск cron
         * @description Значение должно находится в диапазоне от 0 до 59 включительно
         *
         *     Если значение является интервалом, в начало ставится символ '*'
         */
        "Cron_2.Types.Minute": string;
        /** Имя команды cron */
        command: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
