/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение задачи cron */
        "Cron_2.Methods.Commands.Edit": {
            /** Описание задачи */
            description?: string | null;
            days?: import('../../Types/Days.ts').components['schemas']['Cron_2.Types.Days'] | null;
            hh?: import('../../Types/Hour.ts').components['schemas']['Cron_2.Types.Hour'] | null;
            i?: import('../../Types/Minute.ts').components['schemas']['Cron_2.Types.Minute'] | null;
            /** Статус активности задачи */
            on?: boolean | null;
            /** Имя команды cron */
            command: string;
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
        };
        "Cron_2.Methods.Commands.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
