/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Payments": {
            "COUNT(*)"?: unknown;
            "HAS_DOC()"?: unknown;
            id?: unknown;
            external_id?: unknown;
            user_id?: unknown;
            system?: unknown;
            requisites_id?: unknown;
            data?: unknown;
            sum?: unknown;
            currency?: unknown;
            status?: unknown;
            recurrent_type?: unknown;
            tariff_id?: unknown;
            tariff_count_month?: unknown;
            date?: unknown;
            date_month?: unknown;
            date_finished?: unknown;
            date_month_finished?: unknown;
            fromBase64Data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
