/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Экспорт позиций указанных проектов за указанные даты без количественного ограничения
         *
         *     Архив с результатом экспорта будет продублирован на email пользователя */
        "Positions_2.Methods.History.ExportPack.Get": {
            /** Отображать сумму с учетом скидки */
            apply_discount?: boolean;
            /** С какой даты подготовить экспорт */
            date1: import('../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'];
            /** По какую дату подготовить экспорт */
            date2: import('../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'];
        };
        "Positions_2.Methods.History.ExportPack.Get.Exec": unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
