/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Куда добавить запрос
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\AiTracker_2\Types\Prompts\ToType
         * @deprecated
         * @description @deprecated , использовать тип из keywords
         * @enum {string}
         */
        "AiTracker_2.Types.Prompts.ToType": "in_group" | "in_group_last" | "before_keyword" | "after_keyword";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
