/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Имя telegram бота
         * @enum {string}
         */
        "Telegram_2.Types.Bot.Name": "TopvisorBot" | "thundo_bot" | "ApometrBot" | "tv_library_bot" | "tv_wrapped_bot";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
