/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Имя telegram бота
         * @enum {string}
         */
        "Telegram_2.Types.Bot.Name": Telegram_2TypesBotName;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Telegram_2TypesBotName {
    Topvisor = "TopvisorBot",
    Thundo = "ThundoBot",
    Apometr = "ApometrBot",
    Library = "LibraryBot"
}
export type operations = Record<string, never>;
