/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=I18n\Audit\Scan\En */
        "I18n.Audit.Scan": {
            /** @constant */
            readonly Settings: "Audit settings";
            /** @constant */
            readonly Please_add_urls: "Please, add urls for checking";
            /** @constant */
            readonly bar: "bar";
            /** @constant */
            readonly menu: {
                log: "Scan Log";
                summary: "Summary";
                pages: "Pages";
                links: "Links";
                images: "Images";
                js: "JavaScript";
                css: "CSS";
                "domain/common": "Common";
                "pages/summary": "Pages";
                "pages/indexing": "Indexing";
                "pages/content": "Content";
                "pages/schema": "Structured Data";
                "pages/webVitals": "Performance (Core Web Vitals)";
                "pages/og": "Open Graph";
                "links/links": "Links";
                "images/images": "Images";
                "js/js": "JavaScript";
                "css/css": "CSS";
            };
            /** @constant */
            readonly checkInfo: {
                checking: "Checking...";
                time_start: "Started time";
                time_finish: "Finished time";
                "DURATION()": "Duration";
                count_pages: "Pages in audit";
                count_all: "Count finished";
                robot_step: "Current step";
                robot_step_next: "Next step";
            };
            /** @constant */
            readonly checkInfoHints: {
                time_start: "";
                time_finish: "";
                "DURATION()": "";
                count_all: "";
                step: "";
                step_next: "";
            };
            /** @constant */
            readonly checkSteps: {
                genTasks: "Gen Tasks";
                auditSitemap: "Sitemap";
                auditPages: "Check pages";
                auditImages: "Check images";
                auditLinks: "Check links";
                auditJS: "Check JS";
                auditCSS: "Check CSS";
                auditAnalyze: "Analyze";
                save: "Saving";
                closeTask: "Finishing";
            };
            /** @constant */
            readonly summaryCharts: {
                count_pages: "Number of pages";
                count_problems: "Number of problems";
                count_3xx: "3XX";
                count_4xx: "4XX";
                count_5xx: "5XX";
            };
            /** @constant */
            readonly Already_started: "Audit already started";
            /** @constant */
            readonly FilterTime2: "Filter, until the time:";
            /** @constant */
            readonly HTTPCodeHundred0: "No response";
            /** @constant */
            readonly FieldContent: "Text (content)";
            /** @constant */
            readonly FieldTitle: "Text (title)";
            /** @constant */
            readonly FieldBroken: "«Broken»";
            /** @constant */
            readonly FieldCount: "Pages";
            /** @constant */
            readonly FieldHTTPCodes: "Status";
            /** @constant */
            readonly FieldTitleDbl: "Duplicates\nTitle";
            /** @constant */
            readonly FieldDescriptionDbl: "Duplicates\nDescription";
            /** @constant */
            readonly FieldBacklinksInnerCount: "Back Links\ninner";
            /** @constant */
            readonly FieldTextLength: "Text length";
            /** @constant */
            readonly FieldCompression: "Compress";
            /** @constant */
            readonly FieldCacheType: "Cache type";
            /** @constant */
            readonly FieldCacheTime: "Cache time";
            /** @constant */
            readonly FieldCacheValidator: "Cache validator";
            /** @constant */
            readonly FieldRobotsTXTBlocked: "Disallow\nrobots.txt";
            /** @constant */
            readonly FieldCheckRobotsTXTAllowed: "Allow\nrobots.txt";
            /** @constant */
            readonly FieldSitemapXMLMention: "Exists\nsitemap.xml";
            /** @constant */
            readonly FieldLinksCount: "Links";
            /** @constant */
            readonly FieldTLSVersion: "TLS version";
            /** @constant */
            readonly FieldCacheable: "Cacheable";
            /** @constant */
            readonly FieldAlt: "Alt";
            /** @constant */
            readonly FieldSize: "Size";
            /** @constant */
            readonly FieldExtension: "Extension";
            /** @constant */
            readonly FieldContentType: "Content-Type";
            /** @constant */
            readonly FieldModernFormat: "Modern Format";
            /** @constant */
            readonly FieldMinified: "Minified";
            /** @constant */
            readonly FieldRenderBlocking: "Render blocking";
            /** @constant */
            readonly FieldType: "Type";
            /** @constant */
            readonly FieldLoadingTime: "Loading time";
            /** @constant */
            readonly FilterSignalNone: "All checks";
            /** @constant */
            readonly FilterSignalWarnings: "With warnings";
            /** @constant */
            readonly FilterSignalErrors: "With erors";
            /** @constant */
            readonly FilterSignalSignals: "All problems";
            /** @constant */
            readonly DialogPagesWithTitleDbl: "Pages with duplicates Title";
            /** @constant */
            readonly DialogPagesWithDescriptionDbl: "Pages with duplicates Desccription";
            /** @constant */
            readonly DialogPagesWithLink: "Pages with link";
            /** @constant */
            readonly DialogPagesWithImage: "Pages with image";
            /** @constant */
            readonly DialogPagesWithJS: "Pages with JavaScript";
            /** @constant */
            readonly DialogPagesWithCSS: "Pages with CSS";
            /** @constant */
            readonly DialogSummaryPage: "Summary Page";
            /** @constant */
            readonly DialogResources_links: "Links on page";
            /** @constant */
            readonly DialogResources_images: "Images on page";
            /** @constant */
            readonly DialogResources_css: "CSS on page";
            /** @constant */
            readonly DialogResources_js: "JS on page";
            /** @constant */
            readonly Category: "Category";
            /** @constant */
            readonly WhatIsIt: "What is it?";
            /** @constant */
            readonly HowToResolveIt: "How to resolve it?";
            /** @constant */
            readonly Warnings: "Warnings";
            /** @constant */
            readonly Errors: "Errors";
            /** @constant */
            readonly Problems: "All problems";
            /** @constant */
            readonly Hint_not_urls_text: "Add URLs manually or enable website crawling to perform Website Audit.<br>🤖 <a href=\"/website-auditor/\" target=\"_blank\">What Website Audit shows →</a>";
            /** @constant */
            readonly Hint_not_urls_btn: "Add URLs";
            /** @constant */
            readonly Hint_not_checks_text: "You've never launched Website Audit in this project.<br>🤖 <a href=\"/website-auditor/\" target=\"_blank\">What Website Audit shows →</a>";
            /** @constant */
            readonly Hint_not_checks_btn: "Launch Website Audit";
            /** @constant */
            readonly Hint_not_PageSpeed_Insights_API_key_1: "You didn't specify PageSpeed Insights API&#8209;key when launching Website Audit. Add API-key";
            /** @constant */
            readonly Hint_not_PageSpeed_Insights_API_key_2: "in Audit Settings";
            /** @constant */
            readonly Hint_not_PageSpeed_Insights_API_key_3: "and launch Audit once more.";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
