/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Тип графика
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Competitors_2\Types\ByUrl\Charts\Domains\Ads\Type
         * @enum {string}
         */
        "Competitors_2.Types.ByUrl.Charts.Domains.Ads.Type": "small" | "summary" | "count_keywords" | "sum_month_cost_rub_ads" | "sum_month_cost_usd_ads";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
