/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Экспорт отчета в хранилище
         *
         *     После сохранения редиректит в хранилище
         */
        "Positions_2.Methods.History.Export.ToRepository.Get": {
            repository: import('../../../../../Reports_2/Types/Export/Repository.ts').components['schemas']['Reports_2.Types.Export.Repository'];
            output: import('../../../../Types/History/Export/Output.ts').components['schemas']['Positions_2.Types.History.Export.Output'];
            /**
             * Дополнительные параметры экспорта
             *
             *     Возможные поля:
             *     - showSummary
             *     - compact
             *     - splitByGroup
             *
             *     Используются не во всех форматах
             */
            properties?: unknown[];
            painting?: import('../../../../Types/History/Export/Painting.ts').components['schemas']['Positions_2.Types.History.Export.Painting'];
            /**
             * Использовать вкладки
             *
             *     Только для `Output`:
             *     - Xlsx
             *     - Pdf
             */
            with_tabs?: boolean;
            /**
             * Поля (fieldAlias) с привязкой к вкладкам
             *
             *     Только для xlsx с вкладками или pdf
             */
            tabs_fields?: unknown[];
            addWorksheet?: {
                name: string;
                handle: {
                    [key: string]: unknown;
                };
            } | null;
            history_fields?: import('../../../../Types/History/HistoryFields.ts').components['schemas']['Positions_2.Types.History.HistoryFields'] | null;
            /** Индексы регионов */
            regions_indexes: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'];
            /** ID конкурентов */
            competitors_ids?: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /** Добавить в результат данные по топу указанной глубины `tops` */
            show_top_by_depth?: number;
            /**
             * Фильтрация по динамике позиций
             *
             *     Базируется на крайних датах периода.
             *
             *     Игнорируется в режиме сравнения, так как для фильтрации нужны конкретные проект и регион.
             */
            filter_by_dynamic?: import('../../../../Types/History/FilterByDynamics.ts').components['schemas']['Positions_2.Types.History.FilterByDynamics'] | null;
            /**
             * Фильтрация по запросам, позиции которых входят в указанные промежутки
             *
             *     Массив пар значений (min, max)
             *
             *     - Базируется на крайней дате периода отчета
             *     - Игнорируется в режиме сравнения, так как для фильтрации необходимо указывать конкретные проект и регион
             * @description @see \Selector\Types\Operator::Between - Смотрите описание синтаксиса фильтра для `$filter_by_positions`
             */
            filter_by_positions?: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /** При фильтрации по ID папок также искать в подпапках */
            group_folder_id_depth?: boolean;
            /** Показывать удаленные запросы */
            show_trash?: boolean;
            only_exists_first_date?: import('../../../../../Reports_2/Types/OnlyExistsByDateType.ts').components['schemas']['Reports_2.Types.OnlyExistsByDateType'];
            /** Переопределить дату, которую надо использовать для фильтра `$only_exists_first_date` */
            only_exists_by_date?: import('../../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /** ID проекта */
            project_id: number;
            /**
             * Произвольные даты без использования диапазона
             *
             *     Необходимо указать либо `date1`, `date2`, `type_range`, либо `dates` (вместе указывать нельзя)
             */
            dates?: import('../../../../../TV/API/Types/DateArray.ts').components['schemas']['TV.API.Types.DateArray'] | null;
            /**
             * Тип диапазона дат
             * @default 2
             */
            type_range?: import('../../../../../Reports_2/Types/TypeRange.ts').components['schemas']['Reports_2.Types.TypeRange'];
            /**
             * Дата начала диапазона
             *
             *     Используется вместе с date2 для задания диапазона дат
             */
            date1?: import('../../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Дата окончания диапазона
             *
             *     Используется вместе с date1 для задания диапазона дат
             */
            date2?: import('../../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Количество дат в диапазоне
             *
             *     Максимальное значение ограничивается константой MAX_DATES конкретного модуля
             *
             *     Работает совместно с `type_range`
             * @default 31
             */
            count_dates?: number;
            /**
             * Период в днях
             *
             *     Используется для алгоритма получения дат через равные промежутки (`type_range` = 6)
             *
             *     Не более 31
             * @default 7
             */
            period_days?: number;
            /**
             * Список полей объекта, которые надо вернуть в результате
             *
             *     Если запрос поддерживает параметр `fetch_style`, формат ответа может быть разным, `fields` будет влиять на содержание данных в этом ответе
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            fields?: unknown[];
            /**
             * Список полей объекта, по которым необходимо выполнить сортировку
             *
             *     Поля могут быть строками или объектом: {name: string, direction: 'ASC' | 'DESC', orderValues: array, operator: string, values: array}
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            orders?: unknown[];
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
            /**
             * Количество объектов, которые необходимо получить в результате
             *
             *     Используется в паре с offset
             */
            limit?: number | null;
            /**
             * Число объектов, которое необходимо пропустить при получении результата
             *
             *     Используется в паре с limit
             */
            offset?: number;
        };
        "Positions_2.Methods.History.Export.ToRepository.Get.Exec": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
