/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Экспорт файла в хранилище */
        "Audit_2.Methods.Indexing.Export.ToRepository.Get": {
            repository: components["schemas"]["Export_2.Types.Repository.Name"];
            project_id: components["schemas"]["project_id"];
        };
        /**
         * Хранилище для экспорта
         * @enum {string}
         */
        "Export_2.Types.Repository.Name": "gdrive";
        /** ID проекта */
        project_id: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
