/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Валюта шаблонов
         * @enum {string}
         */
        "System_2.Types.Tpl.Currency": System_2TypesTplCurrency;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum System_2TypesTplCurrency {
    Rub = "RUB",
    Usd = "USD",
    Uni = ""
}
export type operations = Record<string, never>;
