/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Экспорт запросов по доменам в проект
         *
         *     Работает только с отчетами по URL по списку доменов с оплаченной схожестью
         */
        "Competitors_2.Methods.Export.ByLeaders.TableToProject.Add": {
            /** @default export_byLeaders_tableToProject */
            func?: string;
            deleted?: boolean | null;
            /** Id проекта */
            project_id: number;
            /** Добавить разделение на группы */
            auto_grouping?: number | null;
            /** Фильтры для поисковых запросов */
            filters_keywords?: unknown[];
            /** Добавить ли в результат url */
            set_targets?: boolean;
            /** Id группы, если не указан будет создана новая группа в указанной папке */
            group_id?: number | null;
            /** Имя группы, если не указан group_id, если группа с таким именем уже существует, то будет исползоваться она */
            group_name?: string | null;
            /**
             * Активность создаваемых групп (по умолчанию: 1 - активные)
             * @default true
             */
            group_on?: boolean;
            /** Переносить ли дубли (по умолчанию: 0 - не переносить) */
            move_duplicate?: boolean;
            /** Id группы для переноса дублей, если не указана будет использован параметр move_duplicate_group_name */
            move_duplicate_group_id?: number | null;
            /** Имя группы для переноса дублей, если группы с таким именем в папке move_duplicate_folder_id нет, она будет создана */
            move_duplicate_group_name?: string | null;
            /** Id папки для переноса дублей, если не указана, то будет использоваться корневая папка проекта */
            move_duplicate_folder_id?: number | null;
            /** Вырезать ли плюсы, точки, запятые, апострофы, кавычки (по умолчанию: 0 - не вырезать) */
            remove_special_chars?: boolean;
            tags?: import('../../../../../Tags_2/Types/TagsIds.ts').components['schemas']['Tags_2.Types.TagsIds'] | null;
            by_type: import('../../../../Types/Report/ByType.ts').components['schemas']['Competitors_2.Types.Report.ByType'];
            /** Индекс региона (не путать с ключом региона) */
            region_index: number;
            /** Ключевая фраза (или ее часть) / url */
            query: string;
            type: import('../../../../Types/Report/Type.ts').components['schemas']['Competitors_2.Types.Report.Type'];
            /** Представление отчета */
            view: string;
            /** Дата проверки */
            date: import('../../../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'];
            /** Ключевая фраза (или ее часть) / url конкурента (для сравнения запросов) */
            query_vs?: string | null;
            /** Тип связи запросов между конкурентами */
            rel_vs?: string | null;
            /** Делать ли проверку на наличие пути в URL (используется при (by_type = url)) */
            strict_query?: boolean;
            /** Минимальная схожесть */
            intersection?: number | null;
            /**
             * Обработчик
             *
             *     Для внутреннего использования
             *
             *     Возможные значения:
             *     - handle
             *     - name
             */
            handler?: unknown;
            /**
             * Список полей объекта, которые надо вернуть в результате
             *
             *     Если запрос поддерживает параметр `fetch_style`, формат ответа может быть разным, `fields` будет влиять на содержание данных в этом ответе
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            fields?: unknown[];
            /**
             * Список полей объекта, по которым необходимо выполнить сортировку
             *
             *     Поля могут быть строками или объектом: {name: string, direction: 'ASC' | 'DESC', orderValues: array, operator: string, values: array}
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            orders?: unknown[];
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
            /**
             * Количество объектов, которые необходимо получить в результате
             *
             *     Используется в паре с offset
             */
            limit?: number | null;
            /**
             * Число объектов, которое необходимо пропустить при получении результата
             *
             *     Используется в паре с limit
             */
            offset?: number;
            /**
             * Определяет формат результата: коллекция, объект, значение
             *
             *     Примеры:
             *     - fetchAll - получить коллекцию объектов
             *     - fetch - получить один объект
             *     - fetchColumn - получить свойсвто объекта
             * @description @see FetchStyle
             *     @see Selector::execFetch() - см. реализацию
             */
            fetch_style?: import('../../../../../Selector/Types/FetchStyle.ts').components['schemas']['Selector.Types.FetchStyle'] | null;
        };
        "Competitors_2.Methods.Export.ByLeaders.TableToProject.Add.Exec": unknown[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
