/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Загрузить и разместить бекап в БД бекапов */
        "Admin_2.Methods.Actions.Backup.Loader.Edit": {
            pass_admin_actions: string;
            /** Сервер, с которого делались бекапы */
            server_name: string;
            /** Имя БД */
            db_name: string;
            /** Имя таблицы */
            table_name: string;
            /** Дата бекапа чата для добавления */
            date: components["schemas"]["TV.API.Types.Date"];
            /** Регулярное выражение для импорта только нужных блоков INSERT
             *
             *     Бекапы хрянятся в .sql файлах с INSERT командами, в одном INSERT может быть много строк */
            insert_filter_regexp?: components["schemas"]["TV.API.Types.RegExp"] | null;
            /** Ключ задачи, участвует в генерации имени БД бекапа
             *
             *     Может потребоваться в случае выполнения одновременных бекапов одной и тоже же таблицы за одну и ту же дату */
            task_key?: string | null;
            /** Являеется ли запуск - тестом */
            test: boolean;
        };
        /**
         * Дата
         * @example 2000-01-01
         */
        "TV.API.Types.Date": string;
        /**
         * Регулярное выражение
         *
         *     Пустое значение разрешено
         *
         *     Управляющие символы "/" в начале и в конце строки будут удалены
         * @example /^year_(\d\d\d\d)$/
         */
        "TV.API.Types.RegExp": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
