/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Перемещение запросов */
        "KeywordsAi_2.Methods.Keywords.Move.Edit": {
            /**
             * Вставить к указанному объекту
             *
             *     Если в to_type указано "Перед или после запроса", то принимает id запроса
             *     Если в to_type указано "В конец или начало группы", то принимает id группы
             */
            to_id: number;
            /** @default in_group */
            to_type?: import('../../../../Keywords_2/Types/Keywords/ToType.ts').components['schemas']['Keywords_2.Types.Keywords.ToType'];
            /** ID проекта */
            project_id: number;
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
        };
        "KeywordsAi_2.Methods.Keywords.Move.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
