/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Минута или интервал в минутах в который должен производиться запуск cron
         * @description Значение должно находится в диапазоне от 0 до 59 включительно
         *
         *     Если значение является интервалом, в начало ставится символ '*'
         */
        "Cron_2.Types.Minute": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
