/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение ключевых слов правила */
        "Mentions_2.Methods.Rules.Keywords.Edit": {
            /** ID проекта */
            project_id: number;
            /** Фразы для изменения */
            keywords: unknown[];
            /** Тип ключевых слов */
            type: import('../../../Types/Rules/Keywords/Type.ts').components['schemas']['Mentions_2.Types.Rules.Keywords.Type'];
            filters: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
        };
        /** @throws Exception */
        "Mentions_2.Methods.Rules.Keywords.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
