/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение цены на расширение группы */
        "Keywords_2.Methods.Collect.Ext.Price.Get": {
            /** Минус фразы */
            keywords_minus?: unknown[] | null;
            /**
             * Отображать сумму с учетом скидки (по умолчанию: 1)
             * @default true
             */
            apply_discount?: boolean;
            /** Каким типом расширять группу */
            type: import('../../../../Types/Collect/Ext/Type.ts').components['schemas']['Keywords_2.Types.Collect.Ext.Type'];
            /** Объекты определителей настроек ПС и регионов */
            qualifiers: import('../../../../Types/Collect/Qualifiers.ts').components['schemas']['Keywords_2.Types.Collect.Qualifiers'];
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
            /** ID проекта */
            project_id: number;
        };
        /** Информация о стоимости запуска подбора запросов */
        "Keywords_2.Methods.Collect.Ext.Price.Get.Exec": {
            pricesByUsers: {
                [key: string]: {
                    price: number;
                    priceOriginal: number;
                    qualifiers: {
                        region_key: number;
                        searcher_key: "0" | "1" | "5" | "100" | "101" | "102" | "104" | "105" | "106";
                        region_lang?: string | null;
                        also_searched?: number | null;
                        depth?: number | null;
                        hint_depth: "1" | "2" | "3";
                        hint_generators: ("letter" | "letter_ru" | "number" | "space")[];
                    };
                    comment: string;
                };
            };
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
