/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение реквизитов */
        "Bank_2.Methods.Requisites.Edit": {
            /** Id реквезитов */
            id: string;
            /** Данные реквезитов
             *
             *     см. объект Bank_2\Objects\Requisites */
            data: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
