/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Имя сегмента, на которые делится период отчета
         *
         *     Отчет делится на равные части - сегменты, за каждый сегмент выводится сводка с агрегацией по этому сегменту
         *
         *     Пример: вывод количества регистраций за каждый **месяц** в отчете
         * @enum {string}
         */
        "Admin_2.Types.Analytics.Segment": Admin_2TypesAnalyticsSegment;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Admin_2TypesAnalyticsSegment {
    Day = "day",
    Month = "month",
    Year = "year"
}
export type operations = Record<string, never>;
