/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отправка проектов на проверку релевантности */
        "Positions_2.Methods.Relevant.Checker.Go.Edit": {
            /** Проверка с учетом фильтра по регионам */
            regions_indexes?: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /** Проверка с учетом фильтра по папкам */
            folders_ids?: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /** При фильтрации по ID папок также проверять в подпапках */
            folders_ids_depth?: boolean;
            /** Проверка с учетом фильтра по группам (сочетается с фильтром folders_ids по логике И) */
            groups_ids?: import('../../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            debug?: import('../../../../../Admin_2/Params/DebugTrait.ts').components['schemas']['Admin_2.Params.DebugTrait']['debug'];
            filters?: import('../../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
        };
        /** Список id проектов, отправленных на проверку */
        "Positions_2.Methods.Relevant.Checker.Go.Edit.Exec": {
            projectIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
