/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Поле с результатом проверки для отчета истории проверок в снимках
         * @enum {string}
         */
        "Snapshots_2.Types.History.HistoryField": "url" | "domain" | "snippet_title" | "snippet_body" | "snippet_ext";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
