/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Поле, возвращаемое в snapshotsData
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Snapshots_2\Types\History\PositionsField
         * @enum {string}
         */
        "Snapshots_2.Types.History.PositionsField": "url" | "domain" | "snippet_title" | "snippet_body" | "snippet_ext";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
