/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Controller_2.Objects.Page": {
            location: components["schemas"]["Controller_2.Objects.Location"];
            openGraph: components["schemas"]["Controller_2.Objects.OpenGraph"];
            options: components["schemas"]["Controller_2.Objects.Page.Options"];
            article: components["schemas"]["Controller_2.Objects.Page.Article"];
            secondMenu: components["schemas"]["Tpl.Core.SecondMenu"];
            leftMenu: components["schemas"]["Tpl.Core.LeftMenu"];
            params: (string | number)[];
            site: components["schemas"]["Controller_2.Objects.Sites.Site"];
            subdomain: string;
            langContext: string;
            langUrl: string;
            modUrl: string;
            mod: string;
            subMod: string;
            /** @default regular */
            theme: string;
            jsonLDs: (string | number)[];
            htmlAttributes: (string | number)[];
            logo: string;
            redirect: string;
            /** @default 302 */
            redirectCode: number;
            tplEngine: components["schemas"]["Controller_2.Objects.TplEngine"];
            tplStaticPath: string;
            tplStatic: string;
            tplStaticRendered: string;
            /** @default templates/pages/content.php */
            tplPath: string;
            tplRendered: string;
            tplSiteRendered: string;
            data: (string | number)[];
            rightsLabels: (string | number)[];
            isFullSize: boolean;
            showFooter: boolean;
            isAdaptive: boolean;
            additionalHeadCode: string;
            v: string;
            vJS: string;
        };
        "Controller_2.Objects.Location": Record<string, never>;
        "Controller_2.Objects.OpenGraph": Record<string, never>;
        "Controller_2.Objects.Page.Options": {
            title: string;
            description: string;
            keywords: string;
            noindex: boolean;
            canonical: string;
            alternates: (string | number)[];
        };
        "Controller_2.Objects.Page.Article": {
            /** @default module */
            type: string;
            duration?: string | null;
            word_count?: string | null;
            htmlRaw: string;
            url: string;
            parent_url: string;
            publish_time?: string | null;
            h1: string;
            description?: string | null;
            menu_name?: string | null;
            intro?: string | null;
            html: string;
            image: string;
            tags: (string | number)[];
            count_views: number;
            count_unique_views?: number | null;
            count_likes: number;
            count_comments?: number | null;
            theme: string;
            noindex: boolean;
            quiz_id: string;
            /** @default ACTIVE */
            state: string;
            rubric_name: string;
            user_id: number;
            user_name?: string | null;
            user_description: string;
            user_avatar: string;
            view: number;
            like: number;
            bookmark: string;
            bookmark_author: string;
            author_alias: string;
        };
        "Tpl.Core.SecondMenu": Record<string, never>;
        "Tpl.Core.LeftMenu": {
            items: (string | number)[];
        };
        "Controller_2.Objects.Sites.Site": Record<string, never>;
        /**
         * Движок работы с шаблонизатором
         * @description Является неотъемлемой частью Page
         */
        "Controller_2.Objects.TplEngine": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
