/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Отмена передачи проекта
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Projects_2\Methods\Rights\ChangeOwner\Del */
        "Projects_2.Methods.Rights.ChangeOwner.Del": {
            /** ID проекта */
            project_id: number;
            /** Почта */
            email: import('../../../../TV/API/Types/Email.ts').components['schemas']['TV.API.Types.Email'];
        };
        "Projects_2.Methods.Rights.ChangeOwner.Del.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
