/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Инициализация передачи проекта другому пользователю */
        "Projects_2.Methods.Rights.ChangeOwner.Edit": {
            /** ID проекта */
            project_id: number;
            /** Почта */
            email: components["schemas"]["TV.API.Types.Email"];
        };
        /**
         * E-mail
         * @example name@example.com
         */
        "TV.API.Types.Email": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
