/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение информации о смене владельца
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Projects_2\Methods\Rights\ChangeOwner\Get
         */
        "Projects_2.Methods.Rights.ChangeOwner.Get": {
            /** ID проекта */
            project_id: number;
        };
        /** email пользователя, которому уже передается проект */
        "Projects_2.Methods.Rights.ChangeOwner.Get.Exec": string | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
