/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Подтип графического объявления
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Broker_2\Types\Ads\Image\Subtype
         * @enum {string}
         */
        "Broker_2.Types.Ads.Image.Subtype": "TEXT_IMAGE_AD" | "MOBILE_APP_IMAGE_AD" | "TEXT_AD_BUILDER_AD" | "MOBILE_APP_AD_BUILDER_AD";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
