/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Получение отчета по проверке индексации
         *
         *     Необходимо указать либо date1 и date2, либо dates (вместе указывать нельзя)
         */
        "Audit_2.Methods.Indexing.Get": {
            /** Вернуть ли заголовки отчета */
            show_headers?: boolean;
            /** Вернуть ли даты проверок */
            show_exists_dates?: boolean;
            /** Вернуть ли суммарное количество страниц в индексе по URL */
            show_counts_indexing?: boolean;
            /**
             * Фильтр по изменениям в указанной ПС в указанную дату
             *
             *     Формат записи: `{{ date }}:{{ searcher_key }}`
             */
            filter_by_alert?: string;
            /**
             * @deprecated
             * @deprecated
             * @default [
             *       "data"
             *     ]
             */
            indexing_fields?: unknown[];
            /**
             * Список полей индексации, которые необходимо получить
             *
             *     См. поля indexing_* в объекте Urls
             */
            history_fields?: import('../../Types/Indexing/History/HistoryFields.ts').components['schemas']['Audit_2.Types.Indexing.History.HistoryFields'] | null;
            searchers_keys: import('../../Types/Indexing/SearcherKeys.ts').components['schemas']['Audit_2.Types.Indexing.SearcherKeys'];
            only_exists_first_date?: import('../../../Reports_2/Types/OnlyExistsByDateType.ts').components['schemas']['Reports_2.Types.OnlyExistsByDateType'];
            /** Переопределить дату, которую надо использовать для фильтра `$only_exists_first_date` */
            only_exists_by_date?: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /** ID проекта */
            project_id: number;
            /**
             * Произвольные даты без использования диапазона
             *
             *     Необходимо указать либо `date1`, `date2`, `type_range`, либо `dates` (вместе указывать нельзя)
             */
            dates?: import('../../../TV/API/Types/DateArray.ts').components['schemas']['TV.API.Types.DateArray'] | null;
            /**
             * Тип диапазона дат
             * @default 2
             */
            type_range?: import('../../../Reports_2/Types/TypeRange.ts').components['schemas']['Reports_2.Types.TypeRange'];
            /**
             * Дата начала диапазона
             *
             *     Используется вместе с date2 для задания диапазона дат
             */
            date1?: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Дата окончания диапазона
             *
             *     Используется вместе с date1 для задания диапазона дат
             */
            date2?: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /**
             * Количество дат в диапазоне
             *
             *     Максимальное значение ограничивается константой MAX_DATES конкретного модуля
             *
             *     Работает совместно с `type_range`
             * @default 31
             */
            count_dates?: number;
            /**
             * Период в днях
             *
             *     Используется для алгоритма получения дат через равные промежутки (`type_range` = 6)
             *
             *     Не более 31
             * @default 7
             */
            period_days?: number;
            /**
             * Список полей объекта, которые надо вернуть в результате
             *
             *     Если запрос поддерживает параметр `fetch_style`, формат ответа может быть разным, `fields` будет влиять на содержание данных в этом ответе
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            fields?: unknown[];
            /**
             * Список полей объекта, по которым необходимо выполнить сортировку
             *
             *     Поля могут быть строками или объектом: {name: string, direction: 'ASC' | 'DESC', orderValues: array, operator: string, values: array}
             *
             *     Использует поля модели
             * @description @see AbstractMethod::MODEL
             */
            orders?: unknown[];
            /**
             * Список фильтров по полям объекта
             *
             *     {name: string, operator: Selector\Types\Operator, values: array}
             *
             *     Использует поля модели
             *
             *     Поля обязательное, если $id не указан
             * @description @see AbstractMethod::MODEL
             *     @see Selector\Types\Operator
             */
            filters?: unknown[];
            /**
             * Id объекта, для фильтрации объектов по id
             *
             *     Только для моделей с полем id
             */
            id?: number | null;
            /**
             * Количество объектов, которые необходимо получить в результате
             *
             *     Используется в паре с offset
             */
            limit?: number | null;
            /**
             * Число объектов, которое необходимо пропустить при получении результата
             *
             *     Используется в паре с limit
             */
            offset?: number;
        };
        /** Список URL с результатами проверок */
        "Audit_2.Methods.Indexing.Get.Exec": import('../../Objects/Indexing/History/Result/Result.ts').components['schemas']['Audit_2.Objects.Indexing.History.Result.Result'];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
