/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование ссылки */
        "Tpvsr_2.Methods.Edit": {
            /** Избранная ссылка */
            favorite?: boolean | null;
            /** Удаленная ссылка */
            deleted?: boolean | null;
            /** Заголовок ссылки */
            title?: string | null;
            /** Хэш ссылки */
            hash?: string | null;
            filters: import('../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
        };
        "Tpvsr_2.Methods.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
