/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получить список оплаченных отчетов */
        "Competitors_2.Methods.Orders.Get": {
            /** Индекс региона (не путать с ключом региона) */
            region_index?: number | null;
            /**
             * - ключевая фраза или ее часть (by_type = keyword)
             *     - url (by_type = url)
             */
            query?: string | null;
            by_type?: import('../../Types/Report/ByType.ts').components['schemas']['Competitors_2.Types.Report.ByType'] | null;
            /** Дата проверки */
            date?: import('../../../TV/API/Types/Date.ts').components['schemas']['TV.API.Types.Date'] | null;
            /** Показать удаленные отчеты */
            deleted?: boolean | null;
        };
        "Competitors_2.Methods.Orders.Get.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
