/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение глубины сбора упоминаний */
        "Mentions_2.Methods.Searchers.Depth.Edit": {
            /** ID проекта */
            project_id: number;
            /** ID правила */
            rule_id: number;
            /** Глубина сбора упоминаний (x100)
             *
             *     От 1 до 10 */
            depth?: number | null;
            filters?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
        };
        "Mentions_2.Methods.Searchers.Depth.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
