/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Название типа. Содержит название провайдера и метода
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Informer_2\Types\Config\Name */
        "Informer_2.Types.Config.Name": {
            method: import('./Method.ts').components['schemas']['Informer_2.Types.Config.Method'];
            provider: import('../Provider.ts').components['schemas']['Informer_2.Types.Provider'];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
