/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Общие статусы для всех проверок в проекте, где проверки имеют свой прогресс
         *
         *     Прогресса нет, например, в задачах wordstat, а статус сбора ядра определяется статусом группы.
         * @enum {integer}
         */
        "Robot_2.Types.ProjectStatus": 0 | 1 | 2 | 3 | 4;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
