/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение записей словаря */
        "Admin_2.Methods.I18n.Get": {
            /** Язык словаря */
            lang?: import('../../../TV/API/Types/Lang.ts').components['schemas']['TV.API.Types.Lang'] | null;
            /** Категория словаря */
            category?: string | null;
            /** Поиск по словарю */
            search?: string | null;
            only_duplicates?: boolean;
        };
        "Admin_2.Methods.I18n.Get.Exec": {
            lang: string;
            category: string;
            name: string;
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
