/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменения подписки сейчас
         *
         *     Выполняет остановку текущей подписки и создает платежку на новую подписку:
         *
         *     - Новая подписка получит скидку на первый платеж с учетом амортизации оплаты на действующую подписку
         *     - После оплаты новой подписки действующая подписка будет досрочно завершена */
        "Payments_2.Methods.Subscriptions.Edit": {
            /** Id следующего плана подписки */
            subscription_plan_id?: string | null;
            /** Значение следующего цикла подписки */
            subscription_cycle?: import('../../../Bank_2/Types/Subscriptions/Cycle.ts').components['schemas']['Bank_2.Types.Subscriptions.Cycle'] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
