/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Установка целевых ссылок по CSV */
        "Keywords_2.Methods.Actions.SetTargetsByKeywords.Edit": {
            /** CSV-строки в формате `keywords;targetUrl` */
            keywords: string;
            /** Изменять только запросы без установленной целевой ссылки */
            only_empty?: boolean;
            /** ID проекта */
            project_id: number;
        };
        "Keywords_2.Methods.Actions.SetTargetsByKeywords.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
