/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Движок, который прикрепляется к ключу
         *
         *     Только ключи с прикрепленным движком могут выполнять задачи такого движка
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Robot_2\Types\Keys\Api
         * @enum {string}
         */
        "Robot_2.Types.Keys.Api": "NONE" | "YANDEX" | "YANDEX_COM" | "YANDEX_TR" | "BRIGHTDATA" | "XML_RIVER" | "XML_STOCK" | "NETNUT" | "PROXYMADATA" | "YANDEX_ASYNC" | "XML_STOCK_IE" | "XML_STOCK_YANDEX_ASYNC" | "XML_RIVER_YANDEX_ASYNC";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
