/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение домена проекта */
        "Admin_2.Methods.Actions.Projects.Domain.Edit": {
            /** ID пользователя */
            userId: number;
            /** Список для замены
             *
             *     Пример: ```
             *     example.com;example2.com
             *     example3.com;example4.com
             *     12345;example5.com
             *     ``` */
            projects: string;
            /** Изменить ли имена проектов */
            needRenameProject: boolean;
            /** Является ли запуск - тестом */
            test: boolean;
        };
        "Admin_2.Methods.Actions.Projects.Domain.Edit.Exec": import('../../../../Objects/Actions/Result.ts').components['schemas']['Admin_2.Objects.Actions.Result'];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
