/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Редактирование прав гостевой ссылки для сервиса проекта */
        "Reports_2.Methods.GuestLink.Edit": {
            /** Сервис отчёта */
            tool_name: import('../../Types/GuestLink/ToolName.ts').components['schemas']['Reports_2.Types.GuestLink.ToolName'];
            /** Доступ к сводке */
            summary?: boolean | null;
            /** Доступ к графикам */
            charts?: boolean | null;
            /** Доступ к конкурентам */
            competitors?: boolean | null;
            /** Доступ к выбору дат */
            calendar?: boolean | null;
            /** Доступ к просмотру частот */
            volumes?: boolean | null;
            /** Доступ к просмотру визитов */
            visitors?: boolean | null;
            /** ID проекта */
            project_id: number;
        };
        "Reports_2.Methods.GuestLink.Edit.Exec": number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
