/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Экспорт истории позиций */
        "Positions_2.Methods.History.Export.Get": {
            output: import('../../../Types/History/Export/Output.ts').components['schemas']['Positions_2.Types.History.Export.Output'];
            /** Индексы регионов */
            regions_indexes: import('../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'];
            /** ID конкурентов */
            competitors_ids?: import('../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            /**
             * Дополнительные параметры экспорта
             *
             *     Возможные поля:
             *     - showSummary
             *     - compact
             *     - splitGroups
             */
            properties?: unknown[];
            painting?: import('../../../Types/History/Export/Painting.ts').components['schemas']['Positions_2.Types.History.Export.Painting'];
            /**
             * Использовать вкладки
             *
             *     Только для `Output`:
             *     - Xlsx
             *     - Pdf
             */
            with_tabs?: boolean;
            /**
             * Поля (fieldAlias) с привязкой к вкладкам
             *
             *     Только для xlsx с вкладками или pdf
             */
            tabs_fields?: unknown[];
            /**
             * Процент попадания в топ
             *
             *     Только для `Output`:
             *      - Xlsx
             *      - Pdf
             *      - Html
             */
            show_top_by_depth?: number;
            /**
             * Если указан, файл будет сохранен в указанной папке и будет возвращен путь к файлу
             *
             *     Для внутреннего использования
             * @description @internal
             */
            returnFilenameFromFolder?: string | null;
            /** // [name => '', handle => ''] */
            addWorksheet?: (string | null) | null;
            /** Искать ли запрос в подпапке */
            group_folder_id_depth?: boolean;
            /** Выбор столбцов данных с результатами проверки */
            positions_fields?: import('../../../Types/History/HistoryFields.ts').components['schemas']['Positions_2.Types.History.HistoryFields'] | null;
            filter_by_dynamic?: import('../../../Types/History/FilterByDynamics.ts').components['schemas']['Positions_2.Types.History.FilterByDynamics'] | null;
            /**
             * Фильтр по позициям
             *
             *     Принимает массив значений, пара из которых берется как промежуток
             *     - `[1,10,50,100]`: поиск между 1 и 10, а также между 50 и 100
             *     - `[1,10,50]`: будет приведено к `[1,10,50,50]`, то есть будет произведен поиск между 1 и 10, а также между 50 и 50
             */
            filter_by_positions?: import('../../../../TV/API/Types/IntArray.ts').components['schemas']['TV.API.Types.IntArray'] | null;
            project_id: import('../../../../TV/API/Params/ProjectIdTrait.ts').components['schemas']['TV.API.Params.ProjectIdTrait']['project_id'];
            dates?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['dates'];
            type_range?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['type_range'];
            date1?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['date1'];
            date2?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['date2'];
            count_dates?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['count_dates'];
            period_days?: import('../../../../TV/API/Params/History/DateRangeTrait.ts').components['schemas']['TV.API.Params.History.DateRangeTrait']['period_days'];
            fields?: import('../../../../TV/API/Params/FieldsTrait.ts').components['schemas']['TV.API.Params.FieldsTrait']['fields'];
            orders?: import('../../../../TV/API/Params/OrdersTrait.ts').components['schemas']['TV.API.Params.OrdersTrait']['orders'];
            filters?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['filters'];
            id?: import('../../../../TV/API/Params/FiltersTrait.ts').components['schemas']['TV.API.Params.FiltersTrait']['id'];
            limit?: import('../../../../TV/API/Params/LimitTrait.ts').components['schemas']['TV.API.Params.LimitTrait']['limit'];
            offset?: import('../../../../TV/API/Params/OffsetTrait.ts').components['schemas']['TV.API.Params.OffsetTrait']['offset'];
        };
        "Positions_2.Methods.History.Export.Get.Exec": unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
