/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Валидация домена для подтверждения оплаты Apple Pay (system = card_ap) */
        "Payments_2.Methods.ValidateMerchantCardAP.Get": {
            /** URL для запроса к Apple Pay */
            validation_url: string;
        };
        "Payments_2.Methods.ValidateMerchantCardAP.Get.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
