/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение валюты пользователя */
        "Admin_2.Methods.Actions.User.Currency.Edit": {
            /** ID пользователя */
            userId: number;
            /** Валюта */
            currency: string;
            /** Являеется ли запуск - тестом */
            test: boolean;
        };
        "Admin_2.Methods.Actions.User.Currency.Edit.Exec": import('../../../../Objects/Actions/Result.ts').components['schemas']['Admin_2.Objects.Actions.Result'];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
