/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Заголовки отчета истории позиций
         * @description @property Positions_2\Types\History\HistoryFields $historyFields
         *     @property list<Project> $projects
         */
        "Positions_2.Objects.History.Headers.Headers": {
            summaries: {
                topsByDepth: {
                    [key: string]: {
                        [key: string]: number;
                    };
                };
                visitors: {
                    [key: string]: number;
                };
            };
            /** Теги сниппетов по хешу */
            snippetsTagsByHash?: {
                [key: string]: unknown;
            } | null;
            /** Название папки, включенной в отчет */
            folderName?: string | null;
            /** Название группы, включенной в отчет */
            groupName?: string | null;
            /** Основной проект */
            projectId: number;
            /** Даты, выводимые в отчете */
            dates: string[];
            /** Запрошенные поля результатов проверок */
            historyFields: import('../../../../TV/API/Types/AbstractEnumArray.ts').components['schemas']['TV.API.Types.AbstractEnumArray'];
            /** Информация о проектах, по которым строится отчет */
            projects: unknown[];
            /**
             * Режим сравнения
             *
             *     Примеры:
             *     - Вывод нескольких проектов
             *     - Вывод нескольких регионов
             *     - Вывод нескольких проектов и регионов
             */
            isCompare: boolean;
            /**
             * Поля элементов отчета
             *
             *     Тип элементов определяется конкретным отчетом, например для проверки позиций это Запросы
             * @description @see static::MODEL
             */
            fields: import('../../../../Selector/Field.ts').components['schemas']['Selector.Field'][];
            /**
             * Фильтры элементов отчета
             *
             *     Для реализации фичей при экспорте отчетов
             * @description @see static::MODEL
             */
            filters: import('../../../../FieldsFilters.ts').components['schemas']['FieldsFilters'][];
            /**
             * Поле для визуальной группировки элементов
             *
             *     Если указно поле, которого нет в элементах, то оно буде игнорироваться
             */
            groupBy: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
