/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Изменение параметров контрагента */
        "Admin_2.Methods.Accounting.Counteragents.Edit": {
            name: string;
            document_number?: string | null;
            comments?: string | null;
            comments_2?: string | null;
        };
        "Admin_2.Methods.Accounting.Counteragents.Edit.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
