/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Операторы сравнения с полем
         * @enum {string}
         */
        FieldOperator: FieldOperator;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum FieldOperator {
    Equals = "EQUALS",
    NotEquals = "NOT_EQUALS",
    In = "IN",
    NotIn = "NOT_IN",
    Greater = "GREATER_THAN",
    GreaterEquals = "GREATER_THAN_EQUALS",
    Less = "LESS_THAN",
    LessEquals = "LESS_THAN_EQUALS",
    Between = "BETWEEN",
    StartsWith = "STARTS_WITH",
    Like = "CONTAINS",
    NotLike = "DOES_NOT_CONTAIN",
    Regexp = "REGEXP",
    NotRegexp = "NOT_REGEXP",
    IsNull = "IS_NULL",
    IsNotNull = "IS_NOT_NULL"
}
export type operations = Record<string, never>;
