/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Поле фильтра */
        FieldFilter: {
            /** Имя поля */
            name?: string;
            operator?: import('./FieldOperator.ts').components['schemas']['FieldOperator'];
            /**
             * Значения для сравнения
             * @description В зависимости от типа условия оно может иметь разное количество значений
             *
             *     Обычно оно имеет только одно значение
             */
            values?: (string | number)[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
