/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Добавление фильтра группы */
        "Admin_2.Methods.Accounting.Group.Filter.Add": {
            /** Id группы */
            group_id: number;
            type: import('../../../../Types/Accounting/Group/FilterType.ts').components['schemas']['Admin_2.Types.Accounting.Group.FilterType'];
            /** Имя контрагента */
            counteragent_name: string;
            /** ИНН контрагента */
            counteragent_inn: string;
            /** Назначение операции */
            purpose?: string | null;
        };
        "Admin_2.Methods.Accounting.Group.Filter.Add.Exec": number | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
