/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Broker.Campaigns": {
            id?: any;
            project_id?: any;
            provider_n?: any;
            campaign_tv_id?: any;
            client_id?: any;
            login?: any;
            agency_name?: any;
            name?: any;
            shows?: any;
            clicks?: any;
            count_tasks?: any;
            frequency?: any;
            rest?: any;
            price?: any;
            timezone?: any;
            currency?: any;
            state?: any;
            servingStatus?: any;
            status_name?: any;
            manualBids?: any;
            no_manage_suspended_keywords?: any;
            added?: any;
            on?: any;
            on_tv?: any;
            off?: any;
            for_off?: any;
            groups_load_time?: any;
            keywords_statistics_update?: any;
            count_keywords?: any;
            count_keywords_autocorrect?: any;
            targeting?: any;
            limits?: any;
            limits_max?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
