/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Models.Audit.Images": {
            "COUNT(*)"?: any;
            "HTTP_CODES_HUNDREDS()"?: (string | number)[] | null;
            check_id?: any;
            url_id?: any;
            url_ids?: any;
            url?: any;
            alt?: any;
            time_parse?: any;
            http_codes?: (string | number)[] | null;
            last_http_code?: any;
            redirects?: (string | number)[] | null;
            locations?: any;
            count?: any;
            ttfb?: any;
            count_pages?: any;
            size?: any;
            cacheable?: any;
            cache_type?: any;
            cache_time?: any;
            cache_validator?: any;
            robots_txt_mention?: any;
            robots_txt_blocked?: any;
            extension?: any;
            content_type?: any;
            modern_format?: any;
            broken?: any;
            search?: any;
            notice?: any;
            error?: any;
            warning_all?: any;
            check_http_code_200?: any;
            check_redirects_not_exists?: any;
            check_redirects_many_not_exists?: any;
            check_ttfb_max?: any;
            check_cacheable?: any;
            check_alt_exists?: any;
            check_alt_length_max?: any;
            check_size_max?: any;
            check_robots_disallow_off?: any;
            check_modern_format?: any;
            count_errors?: any;
            count_warnings?: any;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
