/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Проверка на авторизацию пользователя */
        "Users_2.Methods.Auth.Get": {
            /** Логин авторизации
             *
             *     Может принимать Email|null|emptyString */
            authorisation_login?: string | null;
            /** Пароль авторизации */
            authorisation_pass?: string | null;
        };
        "Users_2.Methods.Auth.Get.Exec": unknown[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
