/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Получение данных доступных столбцов для выборки */
        "Templates_2.Methods.AvailableFieldsData.Get": {
            target_type: import('../../Types/TargetType.ts').components['schemas']['Templates_2.Types.TargetType'];
        };
        /** @throws Exception */
        "Templates_2.Methods.AvailableFieldsData.Get.Exec": Record<string, never>[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
