/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Тип: enum
         *
         *     Принимает: 0|1|false|true
         *
         *     Хранит: false|true
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\Example_2\Types\EnumNumberArray */
        "Example_2.Types.EnumNumberArray": import('./Number.ts').components['schemas']['Example_2.Types.Number'][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
