/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "Example_2.Types.Letter": Example_2TypesLetter;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum Example_2TypesLetter {
    A = "a",
    B = "b",
    C = "c"
}
export type operations = Record<string, never>;
