/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Example_2\Types\User */
        "Example_2.Types.User": {
            name: string;
            email: import('../../TV/API/Types/Email.ts').components['schemas']['TV.API.Types.Email'];
            age: number;
            address: import('./Address.ts').components['schemas']['Example_2.Types.Address'];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
