/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Переименовывание файла
         * @description @see jetbrains://idea/navigate/reference?project=topvisor.com&fqn=Services\System_2\Methods\Cloud\Rename\Edit
         */
        "System_2.Methods.Cloud.Rename.Edit": {
            /** Директория */
            directory: string;
            /** Старое имя файла вместе с расширением */
            basename: string;
            /** Новое имя файла с расширением */
            new_basename: string;
        };
        "System_2.Methods.Cloud.Rename.Edit.Exec": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
