/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Этапы выполнения функции присвоения титулов резульатов года
         *
         *     @see jetbrains://idea/navigate/reference?project=topvisor-com&fqn=Services\Users_2\Types\ResultsYear\Rank\Step
         * @enum {string}
         */
        "Users_2.Types.ResultsYear.Rank.Step": "seoCat" | "activatedTelegramRank" | "auditCheck" | "errorsStatusCode" | "checksPositions" | "projectRegion" | "saintPetersburgChecks" | "moscowChecks" | "topPositions" | "featuredSnippetPositions" | "keywordsClaster" | "googleCashback" | "leaderTopPositions";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
